image:
  registry: ghcr.io
  repositoryOwner: daigo-suhara
  pullPolicy: Always
  tag: latest

core:
  replicaCount: 1
  image:
    repository: dcp-core
  service:
    port: 8080

console:
  replicaCount: 1
  image:
    repository: dcp-console
  service:
    type: LoadBalancer
    port: 8080

cloudrun:
  replicaCount: 1
  image:
    repository: dcp-cloudrun
  service:
    port: 8080

keycloak:
  image:
    repository: quay.io/keycloak/keycloak
    tag: "26.6.1"
  baseUrl: ""
  realm: dcp
  clientId: dcp-core
  clientSecret: ""
  sessionSecret: dcp-session-secret
  adminUsername: admin
  adminPassword: admin
