apiVersion: v2
name: istio
description: Istio control plane and ingress gateway
type: application
version: 0.1.0
dependencies:
  - name: istiod
    version: "1.23.0"
    repository: https://istio-release.storage.googleapis.com/charts
  - name: gateway
    version: "1.23.0"
    repository: https://istio-release.storage.googleapis.com/charts
    alias: ingressgateway
