// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: compute.proto

package computepbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	computepb "github.com/daigo-suhara/dcloud/internal/pb/computepb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ComputeServiceName is the fully-qualified name of the ComputeService service.
	ComputeServiceName = "dcloud.compute.v1.ComputeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ComputeServiceHealthProcedure is the fully-qualified name of the ComputeService's Health RPC.
	ComputeServiceHealthProcedure = "/dcloud.compute.v1.ComputeService/Health"
	// ComputeServiceListMachinesProcedure is the fully-qualified name of the ComputeService's
	// ListMachines RPC.
	ComputeServiceListMachinesProcedure = "/dcloud.compute.v1.ComputeService/ListMachines"
	// ComputeServiceCreateMachineProcedure is the fully-qualified name of the ComputeService's
	// CreateMachine RPC.
	ComputeServiceCreateMachineProcedure = "/dcloud.compute.v1.ComputeService/CreateMachine"
	// ComputeServiceDeleteMachineProcedure is the fully-qualified name of the ComputeService's
	// DeleteMachine RPC.
	ComputeServiceDeleteMachineProcedure = "/dcloud.compute.v1.ComputeService/DeleteMachine"
	// ComputeServiceGetOperationProcedure is the fully-qualified name of the ComputeService's
	// GetOperation RPC.
	ComputeServiceGetOperationProcedure = "/dcloud.compute.v1.ComputeService/GetOperation"
)

// ComputeServiceClient is a client for the dcloud.compute.v1.ComputeService service.
type ComputeServiceClient interface {
	Health(context.Context, *connect.Request[computepb.HealthRequest]) (*connect.Response[computepb.HealthResponse], error)
	ListMachines(context.Context, *connect.Request[computepb.ListMachinesRequest]) (*connect.Response[computepb.ListMachinesResponse], error)
	CreateMachine(context.Context, *connect.Request[computepb.CreateMachineRequest]) (*connect.Response[computepb.CreateMachineResponse], error)
	DeleteMachine(context.Context, *connect.Request[computepb.DeleteMachineRequest]) (*connect.Response[computepb.DeleteMachineResponse], error)
	GetOperation(context.Context, *connect.Request[computepb.GetOperationRequest]) (*connect.Response[computepb.GetOperationResponse], error)
}

// NewComputeServiceClient constructs a client for the dcloud.compute.v1.ComputeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewComputeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ComputeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	computeServiceMethods := computepb.File_compute_proto.Services().ByName("ComputeService").Methods()
	return &computeServiceClient{
		health: connect.NewClient[computepb.HealthRequest, computepb.HealthResponse](
			httpClient,
			baseURL+ComputeServiceHealthProcedure,
			connect.WithSchema(computeServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
		listMachines: connect.NewClient[computepb.ListMachinesRequest, computepb.ListMachinesResponse](
			httpClient,
			baseURL+ComputeServiceListMachinesProcedure,
			connect.WithSchema(computeServiceMethods.ByName("ListMachines")),
			connect.WithClientOptions(opts...),
		),
		createMachine: connect.NewClient[computepb.CreateMachineRequest, computepb.CreateMachineResponse](
			httpClient,
			baseURL+ComputeServiceCreateMachineProcedure,
			connect.WithSchema(computeServiceMethods.ByName("CreateMachine")),
			connect.WithClientOptions(opts...),
		),
		deleteMachine: connect.NewClient[computepb.DeleteMachineRequest, computepb.DeleteMachineResponse](
			httpClient,
			baseURL+ComputeServiceDeleteMachineProcedure,
			connect.WithSchema(computeServiceMethods.ByName("DeleteMachine")),
			connect.WithClientOptions(opts...),
		),
		getOperation: connect.NewClient[computepb.GetOperationRequest, computepb.GetOperationResponse](
			httpClient,
			baseURL+ComputeServiceGetOperationProcedure,
			connect.WithSchema(computeServiceMethods.ByName("GetOperation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// computeServiceClient implements ComputeServiceClient.
type computeServiceClient struct {
	health        *connect.Client[computepb.HealthRequest, computepb.HealthResponse]
	listMachines  *connect.Client[computepb.ListMachinesRequest, computepb.ListMachinesResponse]
	createMachine *connect.Client[computepb.CreateMachineRequest, computepb.CreateMachineResponse]
	deleteMachine *connect.Client[computepb.DeleteMachineRequest, computepb.DeleteMachineResponse]
	getOperation  *connect.Client[computepb.GetOperationRequest, computepb.GetOperationResponse]
}

// Health calls dcloud.compute.v1.ComputeService.Health.
func (c *computeServiceClient) Health(ctx context.Context, req *connect.Request[computepb.HealthRequest]) (*connect.Response[computepb.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// ListMachines calls dcloud.compute.v1.ComputeService.ListMachines.
func (c *computeServiceClient) ListMachines(ctx context.Context, req *connect.Request[computepb.ListMachinesRequest]) (*connect.Response[computepb.ListMachinesResponse], error) {
	return c.listMachines.CallUnary(ctx, req)
}

// CreateMachine calls dcloud.compute.v1.ComputeService.CreateMachine.
func (c *computeServiceClient) CreateMachine(ctx context.Context, req *connect.Request[computepb.CreateMachineRequest]) (*connect.Response[computepb.CreateMachineResponse], error) {
	return c.createMachine.CallUnary(ctx, req)
}

// DeleteMachine calls dcloud.compute.v1.ComputeService.DeleteMachine.
func (c *computeServiceClient) DeleteMachine(ctx context.Context, req *connect.Request[computepb.DeleteMachineRequest]) (*connect.Response[computepb.DeleteMachineResponse], error) {
	return c.deleteMachine.CallUnary(ctx, req)
}

// GetOperation calls dcloud.compute.v1.ComputeService.GetOperation.
func (c *computeServiceClient) GetOperation(ctx context.Context, req *connect.Request[computepb.GetOperationRequest]) (*connect.Response[computepb.GetOperationResponse], error) {
	return c.getOperation.CallUnary(ctx, req)
}

// ComputeServiceHandler is an implementation of the dcloud.compute.v1.ComputeService service.
type ComputeServiceHandler interface {
	Health(context.Context, *connect.Request[computepb.HealthRequest]) (*connect.Response[computepb.HealthResponse], error)
	ListMachines(context.Context, *connect.Request[computepb.ListMachinesRequest]) (*connect.Response[computepb.ListMachinesResponse], error)
	CreateMachine(context.Context, *connect.Request[computepb.CreateMachineRequest]) (*connect.Response[computepb.CreateMachineResponse], error)
	DeleteMachine(context.Context, *connect.Request[computepb.DeleteMachineRequest]) (*connect.Response[computepb.DeleteMachineResponse], error)
	GetOperation(context.Context, *connect.Request[computepb.GetOperationRequest]) (*connect.Response[computepb.GetOperationResponse], error)
}

// NewComputeServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewComputeServiceHandler(svc ComputeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	computeServiceMethods := computepb.File_compute_proto.Services().ByName("ComputeService").Methods()
	computeServiceHealthHandler := connect.NewUnaryHandler(
		ComputeServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(computeServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceListMachinesHandler := connect.NewUnaryHandler(
		ComputeServiceListMachinesProcedure,
		svc.ListMachines,
		connect.WithSchema(computeServiceMethods.ByName("ListMachines")),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceCreateMachineHandler := connect.NewUnaryHandler(
		ComputeServiceCreateMachineProcedure,
		svc.CreateMachine,
		connect.WithSchema(computeServiceMethods.ByName("CreateMachine")),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceDeleteMachineHandler := connect.NewUnaryHandler(
		ComputeServiceDeleteMachineProcedure,
		svc.DeleteMachine,
		connect.WithSchema(computeServiceMethods.ByName("DeleteMachine")),
		connect.WithHandlerOptions(opts...),
	)
	computeServiceGetOperationHandler := connect.NewUnaryHandler(
		ComputeServiceGetOperationProcedure,
		svc.GetOperation,
		connect.WithSchema(computeServiceMethods.ByName("GetOperation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dcloud.compute.v1.ComputeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ComputeServiceHealthProcedure:
			computeServiceHealthHandler.ServeHTTP(w, r)
		case ComputeServiceListMachinesProcedure:
			computeServiceListMachinesHandler.ServeHTTP(w, r)
		case ComputeServiceCreateMachineProcedure:
			computeServiceCreateMachineHandler.ServeHTTP(w, r)
		case ComputeServiceDeleteMachineProcedure:
			computeServiceDeleteMachineHandler.ServeHTTP(w, r)
		case ComputeServiceGetOperationProcedure:
			computeServiceGetOperationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedComputeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedComputeServiceHandler struct{}

func (UnimplementedComputeServiceHandler) Health(context.Context, *connect.Request[computepb.HealthRequest]) (*connect.Response[computepb.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.compute.v1.ComputeService.Health is not implemented"))
}

func (UnimplementedComputeServiceHandler) ListMachines(context.Context, *connect.Request[computepb.ListMachinesRequest]) (*connect.Response[computepb.ListMachinesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.compute.v1.ComputeService.ListMachines is not implemented"))
}

func (UnimplementedComputeServiceHandler) CreateMachine(context.Context, *connect.Request[computepb.CreateMachineRequest]) (*connect.Response[computepb.CreateMachineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.compute.v1.ComputeService.CreateMachine is not implemented"))
}

func (UnimplementedComputeServiceHandler) DeleteMachine(context.Context, *connect.Request[computepb.DeleteMachineRequest]) (*connect.Response[computepb.DeleteMachineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.compute.v1.ComputeService.DeleteMachine is not implemented"))
}

func (UnimplementedComputeServiceHandler) GetOperation(context.Context, *connect.Request[computepb.GetOperationRequest]) (*connect.Response[computepb.GetOperationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.compute.v1.ComputeService.GetOperation is not implemented"))
}
