// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: container.proto

package containerpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	containerpb "github.com/daigo-suhara/dcloud/internal/pb/containerpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ContainerServiceName is the fully-qualified name of the ContainerService service.
	ContainerServiceName = "dcloud.container.v1.ContainerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ContainerServiceHealthProcedure is the fully-qualified name of the ContainerService's Health RPC.
	ContainerServiceHealthProcedure = "/dcloud.container.v1.ContainerService/Health"
	// ContainerServiceListServicesProcedure is the fully-qualified name of the ContainerService's
	// ListServices RPC.
	ContainerServiceListServicesProcedure = "/dcloud.container.v1.ContainerService/ListServices"
	// ContainerServiceDeployServiceProcedure is the fully-qualified name of the ContainerService's
	// DeployService RPC.
	ContainerServiceDeployServiceProcedure = "/dcloud.container.v1.ContainerService/DeployService"
	// ContainerServiceDeleteServiceProcedure is the fully-qualified name of the ContainerService's
	// DeleteService RPC.
	ContainerServiceDeleteServiceProcedure = "/dcloud.container.v1.ContainerService/DeleteService"
	// ContainerServiceGetOperationProcedure is the fully-qualified name of the ContainerService's
	// GetOperation RPC.
	ContainerServiceGetOperationProcedure = "/dcloud.container.v1.ContainerService/GetOperation"
	// ContainerServiceSetServiceDomainProcedure is the fully-qualified name of the ContainerService's
	// SetServiceDomain RPC.
	ContainerServiceSetServiceDomainProcedure = "/dcloud.container.v1.ContainerService/SetServiceDomain"
	// ContainerServiceGetServiceLogsProcedure is the fully-qualified name of the ContainerService's
	// GetServiceLogs RPC.
	ContainerServiceGetServiceLogsProcedure = "/dcloud.container.v1.ContainerService/GetServiceLogs"
)

// ContainerServiceClient is a client for the dcloud.container.v1.ContainerService service.
type ContainerServiceClient interface {
	Health(context.Context, *connect.Request[containerpb.HealthRequest]) (*connect.Response[containerpb.HealthResponse], error)
	ListServices(context.Context, *connect.Request[containerpb.ListServicesRequest]) (*connect.Response[containerpb.ListServicesResponse], error)
	DeployService(context.Context, *connect.Request[containerpb.DeployServiceRequest]) (*connect.Response[containerpb.DeployServiceResponse], error)
	DeleteService(context.Context, *connect.Request[containerpb.DeleteServiceRequest]) (*connect.Response[containerpb.DeleteServiceResponse], error)
	GetOperation(context.Context, *connect.Request[containerpb.GetOperationRequest]) (*connect.Response[containerpb.GetOperationResponse], error)
	SetServiceDomain(context.Context, *connect.Request[containerpb.SetServiceDomainRequest]) (*connect.Response[containerpb.SetServiceDomainResponse], error)
	GetServiceLogs(context.Context, *connect.Request[containerpb.GetServiceLogsRequest]) (*connect.ServerStreamForClient[containerpb.GetServiceLogsResponse], error)
}

// NewContainerServiceClient constructs a client for the dcloud.container.v1.ContainerService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewContainerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ContainerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	containerServiceMethods := containerpb.File_container_proto.Services().ByName("ContainerService").Methods()
	return &containerServiceClient{
		health: connect.NewClient[containerpb.HealthRequest, containerpb.HealthResponse](
			httpClient,
			baseURL+ContainerServiceHealthProcedure,
			connect.WithSchema(containerServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
		listServices: connect.NewClient[containerpb.ListServicesRequest, containerpb.ListServicesResponse](
			httpClient,
			baseURL+ContainerServiceListServicesProcedure,
			connect.WithSchema(containerServiceMethods.ByName("ListServices")),
			connect.WithClientOptions(opts...),
		),
		deployService: connect.NewClient[containerpb.DeployServiceRequest, containerpb.DeployServiceResponse](
			httpClient,
			baseURL+ContainerServiceDeployServiceProcedure,
			connect.WithSchema(containerServiceMethods.ByName("DeployService")),
			connect.WithClientOptions(opts...),
		),
		deleteService: connect.NewClient[containerpb.DeleteServiceRequest, containerpb.DeleteServiceResponse](
			httpClient,
			baseURL+ContainerServiceDeleteServiceProcedure,
			connect.WithSchema(containerServiceMethods.ByName("DeleteService")),
			connect.WithClientOptions(opts...),
		),
		getOperation: connect.NewClient[containerpb.GetOperationRequest, containerpb.GetOperationResponse](
			httpClient,
			baseURL+ContainerServiceGetOperationProcedure,
			connect.WithSchema(containerServiceMethods.ByName("GetOperation")),
			connect.WithClientOptions(opts...),
		),
		setServiceDomain: connect.NewClient[containerpb.SetServiceDomainRequest, containerpb.SetServiceDomainResponse](
			httpClient,
			baseURL+ContainerServiceSetServiceDomainProcedure,
			connect.WithSchema(containerServiceMethods.ByName("SetServiceDomain")),
			connect.WithClientOptions(opts...),
		),
		getServiceLogs: connect.NewClient[containerpb.GetServiceLogsRequest, containerpb.GetServiceLogsResponse](
			httpClient,
			baseURL+ContainerServiceGetServiceLogsProcedure,
			connect.WithSchema(containerServiceMethods.ByName("GetServiceLogs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// containerServiceClient implements ContainerServiceClient.
type containerServiceClient struct {
	health           *connect.Client[containerpb.HealthRequest, containerpb.HealthResponse]
	listServices     *connect.Client[containerpb.ListServicesRequest, containerpb.ListServicesResponse]
	deployService    *connect.Client[containerpb.DeployServiceRequest, containerpb.DeployServiceResponse]
	deleteService    *connect.Client[containerpb.DeleteServiceRequest, containerpb.DeleteServiceResponse]
	getOperation     *connect.Client[containerpb.GetOperationRequest, containerpb.GetOperationResponse]
	setServiceDomain *connect.Client[containerpb.SetServiceDomainRequest, containerpb.SetServiceDomainResponse]
	getServiceLogs   *connect.Client[containerpb.GetServiceLogsRequest, containerpb.GetServiceLogsResponse]
}

// Health calls dcloud.container.v1.ContainerService.Health.
func (c *containerServiceClient) Health(ctx context.Context, req *connect.Request[containerpb.HealthRequest]) (*connect.Response[containerpb.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// ListServices calls dcloud.container.v1.ContainerService.ListServices.
func (c *containerServiceClient) ListServices(ctx context.Context, req *connect.Request[containerpb.ListServicesRequest]) (*connect.Response[containerpb.ListServicesResponse], error) {
	return c.listServices.CallUnary(ctx, req)
}

// DeployService calls dcloud.container.v1.ContainerService.DeployService.
func (c *containerServiceClient) DeployService(ctx context.Context, req *connect.Request[containerpb.DeployServiceRequest]) (*connect.Response[containerpb.DeployServiceResponse], error) {
	return c.deployService.CallUnary(ctx, req)
}

// DeleteService calls dcloud.container.v1.ContainerService.DeleteService.
func (c *containerServiceClient) DeleteService(ctx context.Context, req *connect.Request[containerpb.DeleteServiceRequest]) (*connect.Response[containerpb.DeleteServiceResponse], error) {
	return c.deleteService.CallUnary(ctx, req)
}

// GetOperation calls dcloud.container.v1.ContainerService.GetOperation.
func (c *containerServiceClient) GetOperation(ctx context.Context, req *connect.Request[containerpb.GetOperationRequest]) (*connect.Response[containerpb.GetOperationResponse], error) {
	return c.getOperation.CallUnary(ctx, req)
}

// SetServiceDomain calls dcloud.container.v1.ContainerService.SetServiceDomain.
func (c *containerServiceClient) SetServiceDomain(ctx context.Context, req *connect.Request[containerpb.SetServiceDomainRequest]) (*connect.Response[containerpb.SetServiceDomainResponse], error) {
	return c.setServiceDomain.CallUnary(ctx, req)
}

// GetServiceLogs calls dcloud.container.v1.ContainerService.GetServiceLogs.
func (c *containerServiceClient) GetServiceLogs(ctx context.Context, req *connect.Request[containerpb.GetServiceLogsRequest]) (*connect.ServerStreamForClient[containerpb.GetServiceLogsResponse], error) {
	return c.getServiceLogs.CallServerStream(ctx, req)
}

// ContainerServiceHandler is an implementation of the dcloud.container.v1.ContainerService service.
type ContainerServiceHandler interface {
	Health(context.Context, *connect.Request[containerpb.HealthRequest]) (*connect.Response[containerpb.HealthResponse], error)
	ListServices(context.Context, *connect.Request[containerpb.ListServicesRequest]) (*connect.Response[containerpb.ListServicesResponse], error)
	DeployService(context.Context, *connect.Request[containerpb.DeployServiceRequest]) (*connect.Response[containerpb.DeployServiceResponse], error)
	DeleteService(context.Context, *connect.Request[containerpb.DeleteServiceRequest]) (*connect.Response[containerpb.DeleteServiceResponse], error)
	GetOperation(context.Context, *connect.Request[containerpb.GetOperationRequest]) (*connect.Response[containerpb.GetOperationResponse], error)
	SetServiceDomain(context.Context, *connect.Request[containerpb.SetServiceDomainRequest]) (*connect.Response[containerpb.SetServiceDomainResponse], error)
	GetServiceLogs(context.Context, *connect.Request[containerpb.GetServiceLogsRequest], *connect.ServerStream[containerpb.GetServiceLogsResponse]) error
}

// NewContainerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewContainerServiceHandler(svc ContainerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	containerServiceMethods := containerpb.File_container_proto.Services().ByName("ContainerService").Methods()
	containerServiceHealthHandler := connect.NewUnaryHandler(
		ContainerServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(containerServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	containerServiceListServicesHandler := connect.NewUnaryHandler(
		ContainerServiceListServicesProcedure,
		svc.ListServices,
		connect.WithSchema(containerServiceMethods.ByName("ListServices")),
		connect.WithHandlerOptions(opts...),
	)
	containerServiceDeployServiceHandler := connect.NewUnaryHandler(
		ContainerServiceDeployServiceProcedure,
		svc.DeployService,
		connect.WithSchema(containerServiceMethods.ByName("DeployService")),
		connect.WithHandlerOptions(opts...),
	)
	containerServiceDeleteServiceHandler := connect.NewUnaryHandler(
		ContainerServiceDeleteServiceProcedure,
		svc.DeleteService,
		connect.WithSchema(containerServiceMethods.ByName("DeleteService")),
		connect.WithHandlerOptions(opts...),
	)
	containerServiceGetOperationHandler := connect.NewUnaryHandler(
		ContainerServiceGetOperationProcedure,
		svc.GetOperation,
		connect.WithSchema(containerServiceMethods.ByName("GetOperation")),
		connect.WithHandlerOptions(opts...),
	)
	containerServiceSetServiceDomainHandler := connect.NewUnaryHandler(
		ContainerServiceSetServiceDomainProcedure,
		svc.SetServiceDomain,
		connect.WithSchema(containerServiceMethods.ByName("SetServiceDomain")),
		connect.WithHandlerOptions(opts...),
	)
	containerServiceGetServiceLogsHandler := connect.NewServerStreamHandler(
		ContainerServiceGetServiceLogsProcedure,
		svc.GetServiceLogs,
		connect.WithSchema(containerServiceMethods.ByName("GetServiceLogs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dcloud.container.v1.ContainerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ContainerServiceHealthProcedure:
			containerServiceHealthHandler.ServeHTTP(w, r)
		case ContainerServiceListServicesProcedure:
			containerServiceListServicesHandler.ServeHTTP(w, r)
		case ContainerServiceDeployServiceProcedure:
			containerServiceDeployServiceHandler.ServeHTTP(w, r)
		case ContainerServiceDeleteServiceProcedure:
			containerServiceDeleteServiceHandler.ServeHTTP(w, r)
		case ContainerServiceGetOperationProcedure:
			containerServiceGetOperationHandler.ServeHTTP(w, r)
		case ContainerServiceSetServiceDomainProcedure:
			containerServiceSetServiceDomainHandler.ServeHTTP(w, r)
		case ContainerServiceGetServiceLogsProcedure:
			containerServiceGetServiceLogsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedContainerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedContainerServiceHandler struct{}

func (UnimplementedContainerServiceHandler) Health(context.Context, *connect.Request[containerpb.HealthRequest]) (*connect.Response[containerpb.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.container.v1.ContainerService.Health is not implemented"))
}

func (UnimplementedContainerServiceHandler) ListServices(context.Context, *connect.Request[containerpb.ListServicesRequest]) (*connect.Response[containerpb.ListServicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.container.v1.ContainerService.ListServices is not implemented"))
}

func (UnimplementedContainerServiceHandler) DeployService(context.Context, *connect.Request[containerpb.DeployServiceRequest]) (*connect.Response[containerpb.DeployServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.container.v1.ContainerService.DeployService is not implemented"))
}

func (UnimplementedContainerServiceHandler) DeleteService(context.Context, *connect.Request[containerpb.DeleteServiceRequest]) (*connect.Response[containerpb.DeleteServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.container.v1.ContainerService.DeleteService is not implemented"))
}

func (UnimplementedContainerServiceHandler) GetOperation(context.Context, *connect.Request[containerpb.GetOperationRequest]) (*connect.Response[containerpb.GetOperationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.container.v1.ContainerService.GetOperation is not implemented"))
}

func (UnimplementedContainerServiceHandler) SetServiceDomain(context.Context, *connect.Request[containerpb.SetServiceDomainRequest]) (*connect.Response[containerpb.SetServiceDomainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.container.v1.ContainerService.SetServiceDomain is not implemented"))
}

func (UnimplementedContainerServiceHandler) GetServiceLogs(context.Context, *connect.Request[containerpb.GetServiceLogsRequest], *connect.ServerStream[containerpb.GetServiceLogsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.container.v1.ContainerService.GetServiceLogs is not implemented"))
}
