apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: {{ include "dcloud.fullname" . }}-container
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: container
spec:
  replicas: {{ .Values.container.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: container
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: container
    spec:
      serviceAccountName: {{ include "dcloud.fullname" . }}-internal
      containers:
        - name: container
          image: {{ include "dcloud.image" (dict "root" . "repository" .Values.container.image.repository) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "dcloud.fullname" . }}-database
          env:
            - name: DCLD_PUBLIC_SERVICE_DOMAIN
              value: {{ .Values.publicServiceDomain | quote }}
            - name: DCLD_IDENTITY_JWKS_URL
              value: {{ include "dcloud.jwksURL" . | quote }}
            - name: DCLD_CONTAINER_RUNTIME_CLASS
              value: {{ .Values.container.runtimeClassName | default "" | quote }}
          ports:
            - name: grpc
              containerPort: {{ .Values.container.service.port }}
            - name: http
              containerPort: {{ .Values.container.service.httpPort }}
          readinessProbe:
            tcpSocket:
              port: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcloud.fullname" . }}-container
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: container
spec:
  ports:
    - name: grpc
      port: {{ .Values.container.service.port }}
      targetPort: grpc
    - name: http
      port: {{ .Values.container.service.httpPort }}
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: container
