apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dcloud.fullname" . }}-database
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: database
    spec:
      serviceAccountName: {{ include "dcloud.fullname" . }}-internal
      containers:
        - name: database
          image: {{ include "dcloud.image" (dict "root" . "repository" .Values.database.image.repository) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "dcloud.fullname" . }}-database
          env:
            - name: DCLD_DATABASE_ADDR
              value: :{{ .Values.database.service.port }}
            - name: DCLD_DATABASE_STORAGE_CLASS
              value: {{ .Values.database.storageClass }}
          ports:
            - name: grpc
              containerPort: {{ .Values.database.service.port }}
          readinessProbe:
            tcpSocket:
              port: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcloud.fullname" . }}-database
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  ports:
    - name: grpc
      port: {{ .Values.database.service.port }}
      targetPort: grpc
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
