apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dcloud.fullname" . }}-identity
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
spec:
  replicas: {{ .Values.identity.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: identity
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: identity
    spec:
      containers:
        - name: identity
          image: {{ include "dcloud.image" (dict "root" . "repository" .Values.identity.image.repository) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "dcloud.fullname" . }}-database
          env:
            - name: DCLD_IDENTITY_ADDR
              value: :{{ .Values.identity.service.port }}
          ports:
            - name: grpc
              containerPort: {{ .Values.identity.service.port }}
          readinessProbe:
            tcpSocket:
              port: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcloud.fullname" . }}-identity
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
spec:
  ports:
    - name: grpc
      port: {{ .Values.identity.service.port }}
      targetPort: grpc
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: identity
