{{- if .Values.knative.enabled }}
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
  config:
    domain:
      {{ .Values.publicServiceDomain }}: ""
    network:
      autocreate-cluster-domain-claims: "true"
      ingress-class: "kourier.ingress.networking.knative.dev"
    features:
      kubernetes.podspec-securitycontext: enabled
      kubernetes.podspec-volumes-emptydir: enabled
      kubernetes.podspec-fieldref: enabled
      kubernetes.containerspec-addcapabilities: enabled
{{- end }}
