apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dcloud.fullname" . }}-objectstorage
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: objectstorage
spec:
  replicas: {{ .Values.objectstorage.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: objectstorage
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: objectstorage
    spec:
      serviceAccountName: {{ include "dcloud.fullname" . }}-internal
      containers:
        - name: objectstorage
          image: {{ include "dcloud.image" (dict "root" . "repository" .Values.objectstorage.image.repository) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "dcloud.fullname" . }}-database
          env:
            - name: DCLD_STORAGE_ADDR
              value: :{{ .Values.objectstorage.service.port }}
            - name: DCLD_BUCKET_STORAGE_CLASS
              value: {{ .Values.objectstorage.bucketStorageClass }}
            - name: DCLD_RGW_ENDPOINT
              value: {{ .Values.objectstorage.rgwEndpoint }}
          ports:
            - name: grpc
              containerPort: {{ .Values.objectstorage.service.port }}
          readinessProbe:
            tcpSocket:
              port: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcloud.fullname" . }}-objectstorage
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: objectstorage
spec:
  ports:
    - name: grpc
      port: {{ .Values.objectstorage.service.port }}
      targetPort: grpc
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: objectstorage
