apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dcloud.fullname" . }}-storage
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  replicas: {{ .Values.storage.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: storage
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: storage
    spec:
      serviceAccountName: {{ include "dcloud.fullname" . }}-internal
      containers:
        - name: storage
          image: {{ include "dcloud.image" (dict "root" . "repository" .Values.storage.image.repository) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "dcloud.fullname" . }}-database
          env:
            - name: DCLD_STORAGE_ADDR
              value: :{{ .Values.storage.service.port }}
            - name: DCLD_BUCKET_STORAGE_CLASS
              value: {{ .Values.storage.bucketStorageClass }}
            - name: DCLD_RGW_ENDPOINT
              value: {{ .Values.storage.rgwEndpoint }}
          ports:
            - name: grpc
              containerPort: {{ .Values.storage.service.port }}
          readinessProbe:
            tcpSocket:
              port: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcloud.fullname" . }}-storage
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  ports:
    - name: grpc
      port: {{ .Values.storage.service.port }}
      targetPort: grpc
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: storage
