// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: project.proto

package projectpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{1}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type PlatformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformRequest) Reset() {
	*x = PlatformRequest{}
	mi := &file_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformRequest) ProtoMessage() {}

func (x *PlatformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformRequest.ProtoReflect.Descriptor instead.
func (*PlatformRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{3}
}

type PlatformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Components    []string               `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformResponse) Reset() {
	*x = PlatformResponse{}
	mi := &file_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformResponse) ProtoMessage() {}

func (x *PlatformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformResponse.ProtoReflect.Descriptor instead.
func (*PlatformResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{4}
}

func (x *PlatformResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlatformResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlatformResponse) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Deleting      bool                   `protobuf:"varint,5,opt,name=deleting,proto3" json:"deleting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{5}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Project) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Project) GetDeleting() bool {
	if x != nil {
		return x.Deleting
	}
	return false
}

type ProjectRepository struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProjectId        string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RepositoryOwner  string                 `protobuf:"bytes,3,opt,name=repository_owner,json=repositoryOwner,proto3" json:"repository_owner,omitempty"`
	RepositoryName   string                 `protobuf:"bytes,4,opt,name=repository_name,json=repositoryName,proto3" json:"repository_name,omitempty"`
	RepositoryBranch string                 `protobuf:"bytes,5,opt,name=repository_branch,json=repositoryBranch,proto3" json:"repository_branch,omitempty"`
	ConnectedAt      string                 `protobuf:"bytes,6,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProjectRepository) Reset() {
	*x = ProjectRepository{}
	mi := &file_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRepository) ProtoMessage() {}

func (x *ProjectRepository) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRepository.ProtoReflect.Descriptor instead.
func (*ProjectRepository) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectRepository) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectRepository) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProjectRepository) GetRepositoryOwner() string {
	if x != nil {
		return x.RepositoryOwner
	}
	return ""
}

func (x *ProjectRepository) GetRepositoryName() string {
	if x != nil {
		return x.RepositoryName
	}
	return ""
}

func (x *ProjectRepository) GetRepositoryBranch() string {
	if x != nil {
		return x.RepositoryBranch
	}
	return ""
}

func (x *ProjectRepository) GetConnectedAt() string {
	if x != nil {
		return x.ConnectedAt
	}
	return ""
}

func (x *ProjectRepository) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type IsProjectDeletingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsProjectDeletingRequest) Reset() {
	*x = IsProjectDeletingRequest{}
	mi := &file_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsProjectDeletingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsProjectDeletingRequest) ProtoMessage() {}

func (x *IsProjectDeletingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsProjectDeletingRequest.ProtoReflect.Descriptor instead.
func (*IsProjectDeletingRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{7}
}

func (x *IsProjectDeletingRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type IsProjectDeletingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleting      bool                   `protobuf:"varint,1,opt,name=deleting,proto3" json:"deleting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsProjectDeletingResponse) Reset() {
	*x = IsProjectDeletingResponse{}
	mi := &file_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsProjectDeletingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsProjectDeletingResponse) ProtoMessage() {}

func (x *IsProjectDeletingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsProjectDeletingResponse.ProtoReflect.Descriptor instead.
func (*IsProjectDeletingResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{8}
}

func (x *IsProjectDeletingResponse) GetDeleting() bool {
	if x != nil {
		return x.Deleting
	}
	return false
}

type ProjectExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectExistsRequest) Reset() {
	*x = ProjectExistsRequest{}
	mi := &file_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectExistsRequest) ProtoMessage() {}

func (x *ProjectExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectExistsRequest.ProtoReflect.Descriptor instead.
func (*ProjectExistsRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectExistsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProjectExistsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ProjectExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectExistsResponse) Reset() {
	*x = ProjectExistsResponse{}
	mi := &file_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectExistsResponse) ProtoMessage() {}

func (x *ProjectExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectExistsResponse.ProtoReflect.Descriptor instead.
func (*ProjectExistsResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{10}
}

func (x *ProjectExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type GetProjectRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRepositoryRequest) Reset() {
	*x = GetProjectRepositoryRequest{}
	mi := &file_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRepositoryRequest) ProtoMessage() {}

func (x *GetProjectRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRepositoryRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{11}
}

func (x *GetProjectRepositoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProjectRepositoryRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *ProjectRepository     `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRepositoryResponse) Reset() {
	*x = GetProjectRepositoryResponse{}
	mi := &file_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRepositoryResponse) ProtoMessage() {}

func (x *GetProjectRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRepositoryResponse.ProtoReflect.Descriptor instead.
func (*GetProjectRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{12}
}

func (x *GetProjectRepositoryResponse) GetRepository() *ProjectRepository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type UpsertProjectRepositoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId        string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RepositoryOwner  string                 `protobuf:"bytes,3,opt,name=repository_owner,json=repositoryOwner,proto3" json:"repository_owner,omitempty"`
	RepositoryName   string                 `protobuf:"bytes,4,opt,name=repository_name,json=repositoryName,proto3" json:"repository_name,omitempty"`
	RepositoryBranch string                 `protobuf:"bytes,5,opt,name=repository_branch,json=repositoryBranch,proto3" json:"repository_branch,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpsertProjectRepositoryRequest) Reset() {
	*x = UpsertProjectRepositoryRequest{}
	mi := &file_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProjectRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProjectRepositoryRequest) ProtoMessage() {}

func (x *UpsertProjectRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProjectRepositoryRequest.ProtoReflect.Descriptor instead.
func (*UpsertProjectRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertProjectRepositoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertProjectRepositoryRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpsertProjectRepositoryRequest) GetRepositoryOwner() string {
	if x != nil {
		return x.RepositoryOwner
	}
	return ""
}

func (x *UpsertProjectRepositoryRequest) GetRepositoryName() string {
	if x != nil {
		return x.RepositoryName
	}
	return ""
}

func (x *UpsertProjectRepositoryRequest) GetRepositoryBranch() string {
	if x != nil {
		return x.RepositoryBranch
	}
	return ""
}

type UpsertProjectRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *ProjectRepository     `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProjectRepositoryResponse) Reset() {
	*x = UpsertProjectRepositoryResponse{}
	mi := &file_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProjectRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProjectRepositoryResponse) ProtoMessage() {}

func (x *UpsertProjectRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProjectRepositoryResponse.ProtoReflect.Descriptor instead.
func (*UpsertProjectRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{14}
}

func (x *UpsertProjectRepositoryResponse) GetRepository() *ProjectRepository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type CreateProjectDeleteOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectDeleteOperationRequest) Reset() {
	*x = CreateProjectDeleteOperationRequest{}
	mi := &file_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectDeleteOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectDeleteOperationRequest) ProtoMessage() {}

func (x *CreateProjectDeleteOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectDeleteOperationRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectDeleteOperationRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{15}
}

func (x *CreateProjectDeleteOperationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProjectDeleteOperationRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type CreateProjectDeleteOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectDeleteOperationResponse) Reset() {
	*x = CreateProjectDeleteOperationResponse{}
	mi := &file_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectDeleteOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectDeleteOperationResponse) ProtoMessage() {}

func (x *CreateProjectDeleteOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectDeleteOperationResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectDeleteOperationResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{16}
}

func (x *CreateProjectDeleteOperationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_project_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{17}
}

func (x *ListProjectsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Projects      []*Project             `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_project_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{18}
}

func (x *ListProjectsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_project_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{19}
}

func (x *CreateProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_project_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{20}
}

func (x *CreateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_project_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type DeleteProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_project_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_project_proto_rawDescGZIP(), []int{22}
}

var File_project_proto protoreflect.FileDescriptor

const file_project_proto_rawDesc = "" +
	"\n" +
	"\rproject.proto\x12\x11dcloud.project.v1\"\a\n" +
	"\x05Empty\"\x0f\n" +
	"\rHealthRequest\"`\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"\x11\n" +
	"\x0fPlatformRequest\"h\n" +
	"\x10PlatformResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"components\x18\x03 \x03(\tR\n" +
	"components\"~\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\bdeleting\x18\x05 \x01(\bR\bdeleting\"\x8e\x02\n" +
	"\x11ProjectRepository\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x10repository_owner\x18\x03 \x01(\tR\x0frepositoryOwner\x12'\n" +
	"\x0frepository_name\x18\x04 \x01(\tR\x0erepositoryName\x12+\n" +
	"\x11repository_branch\x18\x05 \x01(\tR\x10repositoryBranch\x12!\n" +
	"\fconnected_at\x18\x06 \x01(\tR\vconnectedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"9\n" +
	"\x18IsProjectDeletingRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"7\n" +
	"\x19IsProjectDeletingResponse\x12\x1a\n" +
	"\bdeleting\x18\x01 \x01(\bR\bdeleting\"N\n" +
	"\x14ProjectExistsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"/\n" +
	"\x15ProjectExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"U\n" +
	"\x1bGetProjectRepositoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"d\n" +
	"\x1cGetProjectRepositoryResponse\x12D\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2$.dcloud.project.v1.ProjectRepositoryR\n" +
	"repository\"\xd9\x01\n" +
	"\x1eUpsertProjectRepositoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12)\n" +
	"\x10repository_owner\x18\x03 \x01(\tR\x0frepositoryOwner\x12'\n" +
	"\x0frepository_name\x18\x04 \x01(\tR\x0erepositoryName\x12+\n" +
	"\x11repository_branch\x18\x05 \x01(\tR\x10repositoryBranch\"g\n" +
	"\x1fUpsertProjectRepositoryResponse\x12D\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2$.dcloud.project.v1.ProjectRepositoryR\n" +
	"repository\"]\n" +
	"#CreateProjectDeleteOperationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"I\n" +
	"$CreateProjectDeleteOperationResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\".\n" +
	"\x13ListProjectsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"g\n" +
	"\x14ListProjectsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x126\n" +
	"\bprojects\x18\x02 \x03(\v2\x1a.dcloud.project.v1.ProjectR\bprojects\"C\n" +
	"\x14CreateProjectRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"M\n" +
	"\x15CreateProjectResponse\x124\n" +
	"\aproject\x18\x01 \x01(\v2\x1a.dcloud.project.v1.ProjectR\aproject\"N\n" +
	"\x14DeleteProjectRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\x17\n" +
	"\x15DeleteProjectResponse2\xbf\b\n" +
	"\x0eProjectService\x12M\n" +
	"\x06Health\x12 .dcloud.project.v1.HealthRequest\x1a!.dcloud.project.v1.HealthResponse\x12S\n" +
	"\bPlatform\x12\".dcloud.project.v1.PlatformRequest\x1a#.dcloud.project.v1.PlatformResponse\x12_\n" +
	"\fListProjects\x12&.dcloud.project.v1.ListProjectsRequest\x1a'.dcloud.project.v1.ListProjectsResponse\x12b\n" +
	"\rCreateProject\x12'.dcloud.project.v1.CreateProjectRequest\x1a(.dcloud.project.v1.CreateProjectResponse\x12b\n" +
	"\rDeleteProject\x12'.dcloud.project.v1.DeleteProjectRequest\x1a(.dcloud.project.v1.DeleteProjectResponse\x12n\n" +
	"\x11IsProjectDeleting\x12+.dcloud.project.v1.IsProjectDeletingRequest\x1a,.dcloud.project.v1.IsProjectDeletingResponse\x12b\n" +
	"\rProjectExists\x12'.dcloud.project.v1.ProjectExistsRequest\x1a(.dcloud.project.v1.ProjectExistsResponse\x12w\n" +
	"\x14GetProjectRepository\x12..dcloud.project.v1.GetProjectRepositoryRequest\x1a/.dcloud.project.v1.GetProjectRepositoryResponse\x12\x80\x01\n" +
	"\x17UpsertProjectRepository\x121.dcloud.project.v1.UpsertProjectRepositoryRequest\x1a2.dcloud.project.v1.UpsertProjectRepositoryResponse\x12\x8f\x01\n" +
	"\x1cCreateProjectDeleteOperation\x126.dcloud.project.v1.CreateProjectDeleteOperationRequest\x1a7.dcloud.project.v1.CreateProjectDeleteOperationResponseB@Z>github.com/daigo-suhara/dcloud/internal/pb/projectpb;projectpbb\x06proto3"

var (
	file_project_proto_rawDescOnce sync.Once
	file_project_proto_rawDescData []byte
)

func file_project_proto_rawDescGZIP() []byte {
	file_project_proto_rawDescOnce.Do(func() {
		file_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)))
	})
	return file_project_proto_rawDescData
}

var file_project_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_project_proto_goTypes = []any{
	(*Empty)(nil),                                // 0: dcloud.project.v1.Empty
	(*HealthRequest)(nil),                        // 1: dcloud.project.v1.HealthRequest
	(*HealthResponse)(nil),                       // 2: dcloud.project.v1.HealthResponse
	(*PlatformRequest)(nil),                      // 3: dcloud.project.v1.PlatformRequest
	(*PlatformResponse)(nil),                     // 4: dcloud.project.v1.PlatformResponse
	(*Project)(nil),                              // 5: dcloud.project.v1.Project
	(*ProjectRepository)(nil),                    // 6: dcloud.project.v1.ProjectRepository
	(*IsProjectDeletingRequest)(nil),             // 7: dcloud.project.v1.IsProjectDeletingRequest
	(*IsProjectDeletingResponse)(nil),            // 8: dcloud.project.v1.IsProjectDeletingResponse
	(*ProjectExistsRequest)(nil),                 // 9: dcloud.project.v1.ProjectExistsRequest
	(*ProjectExistsResponse)(nil),                // 10: dcloud.project.v1.ProjectExistsResponse
	(*GetProjectRepositoryRequest)(nil),          // 11: dcloud.project.v1.GetProjectRepositoryRequest
	(*GetProjectRepositoryResponse)(nil),         // 12: dcloud.project.v1.GetProjectRepositoryResponse
	(*UpsertProjectRepositoryRequest)(nil),       // 13: dcloud.project.v1.UpsertProjectRepositoryRequest
	(*UpsertProjectRepositoryResponse)(nil),      // 14: dcloud.project.v1.UpsertProjectRepositoryResponse
	(*CreateProjectDeleteOperationRequest)(nil),  // 15: dcloud.project.v1.CreateProjectDeleteOperationRequest
	(*CreateProjectDeleteOperationResponse)(nil), // 16: dcloud.project.v1.CreateProjectDeleteOperationResponse
	(*ListProjectsRequest)(nil),                  // 17: dcloud.project.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),                 // 18: dcloud.project.v1.ListProjectsResponse
	(*CreateProjectRequest)(nil),                 // 19: dcloud.project.v1.CreateProjectRequest
	(*CreateProjectResponse)(nil),                // 20: dcloud.project.v1.CreateProjectResponse
	(*DeleteProjectRequest)(nil),                 // 21: dcloud.project.v1.DeleteProjectRequest
	(*DeleteProjectResponse)(nil),                // 22: dcloud.project.v1.DeleteProjectResponse
}
var file_project_proto_depIdxs = []int32{
	6,  // 0: dcloud.project.v1.GetProjectRepositoryResponse.repository:type_name -> dcloud.project.v1.ProjectRepository
	6,  // 1: dcloud.project.v1.UpsertProjectRepositoryResponse.repository:type_name -> dcloud.project.v1.ProjectRepository
	5,  // 2: dcloud.project.v1.ListProjectsResponse.projects:type_name -> dcloud.project.v1.Project
	5,  // 3: dcloud.project.v1.CreateProjectResponse.project:type_name -> dcloud.project.v1.Project
	1,  // 4: dcloud.project.v1.ProjectService.Health:input_type -> dcloud.project.v1.HealthRequest
	3,  // 5: dcloud.project.v1.ProjectService.Platform:input_type -> dcloud.project.v1.PlatformRequest
	17, // 6: dcloud.project.v1.ProjectService.ListProjects:input_type -> dcloud.project.v1.ListProjectsRequest
	19, // 7: dcloud.project.v1.ProjectService.CreateProject:input_type -> dcloud.project.v1.CreateProjectRequest
	21, // 8: dcloud.project.v1.ProjectService.DeleteProject:input_type -> dcloud.project.v1.DeleteProjectRequest
	7,  // 9: dcloud.project.v1.ProjectService.IsProjectDeleting:input_type -> dcloud.project.v1.IsProjectDeletingRequest
	9,  // 10: dcloud.project.v1.ProjectService.ProjectExists:input_type -> dcloud.project.v1.ProjectExistsRequest
	11, // 11: dcloud.project.v1.ProjectService.GetProjectRepository:input_type -> dcloud.project.v1.GetProjectRepositoryRequest
	13, // 12: dcloud.project.v1.ProjectService.UpsertProjectRepository:input_type -> dcloud.project.v1.UpsertProjectRepositoryRequest
	15, // 13: dcloud.project.v1.ProjectService.CreateProjectDeleteOperation:input_type -> dcloud.project.v1.CreateProjectDeleteOperationRequest
	2,  // 14: dcloud.project.v1.ProjectService.Health:output_type -> dcloud.project.v1.HealthResponse
	4,  // 15: dcloud.project.v1.ProjectService.Platform:output_type -> dcloud.project.v1.PlatformResponse
	18, // 16: dcloud.project.v1.ProjectService.ListProjects:output_type -> dcloud.project.v1.ListProjectsResponse
	20, // 17: dcloud.project.v1.ProjectService.CreateProject:output_type -> dcloud.project.v1.CreateProjectResponse
	22, // 18: dcloud.project.v1.ProjectService.DeleteProject:output_type -> dcloud.project.v1.DeleteProjectResponse
	8,  // 19: dcloud.project.v1.ProjectService.IsProjectDeleting:output_type -> dcloud.project.v1.IsProjectDeletingResponse
	10, // 20: dcloud.project.v1.ProjectService.ProjectExists:output_type -> dcloud.project.v1.ProjectExistsResponse
	12, // 21: dcloud.project.v1.ProjectService.GetProjectRepository:output_type -> dcloud.project.v1.GetProjectRepositoryResponse
	14, // 22: dcloud.project.v1.ProjectService.UpsertProjectRepository:output_type -> dcloud.project.v1.UpsertProjectRepositoryResponse
	16, // 23: dcloud.project.v1.ProjectService.CreateProjectDeleteOperation:output_type -> dcloud.project.v1.CreateProjectDeleteOperationResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_project_proto_init() }
func file_project_proto_init() {
	if File_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_proto_rawDesc), len(file_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_proto_goTypes,
		DependencyIndexes: file_project_proto_depIdxs,
		MessageInfos:      file_project_proto_msgTypes,
	}.Build()
	File_project_proto = out.File
	file_project_proto_goTypes = nil
	file_project_proto_depIdxs = nil
}
