apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dcp.fullname" . }}-cloudrun
  labels:
    {{- include "dcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudrun
spec:
  replicas: {{ .Values.cloudrun.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: cloudrun
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: cloudrun
    spec:
      containers:
        - name: cloudrun
          image: {{ include "dcp.image" (dict "root" . "repository" .Values.cloudrun.image.repository) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcp.fullname" . }}-cloudrun
  labels:
    {{- include "dcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudrun
spec:
  ports:
    - name: http
      port: {{ .Values.cloudrun.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cloudrun
