// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: database.proto

package databasepbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	databasepb "github.com/daigo-suhara/dcloud/internal/pb/databasepb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DatabaseServiceName is the fully-qualified name of the DatabaseService service.
	DatabaseServiceName = "dcloud.database.v1.DatabaseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DatabaseServiceHealthProcedure is the fully-qualified name of the DatabaseService's Health RPC.
	DatabaseServiceHealthProcedure = "/dcloud.database.v1.DatabaseService/Health"
	// DatabaseServiceListDatabasesProcedure is the fully-qualified name of the DatabaseService's
	// ListDatabases RPC.
	DatabaseServiceListDatabasesProcedure = "/dcloud.database.v1.DatabaseService/ListDatabases"
	// DatabaseServiceCreateDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// CreateDatabase RPC.
	DatabaseServiceCreateDatabaseProcedure = "/dcloud.database.v1.DatabaseService/CreateDatabase"
	// DatabaseServiceDeleteDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// DeleteDatabase RPC.
	DatabaseServiceDeleteDatabaseProcedure = "/dcloud.database.v1.DatabaseService/DeleteDatabase"
	// DatabaseServiceGetDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// GetDatabase RPC.
	DatabaseServiceGetDatabaseProcedure = "/dcloud.database.v1.DatabaseService/GetDatabase"
	// DatabaseServiceGetConnectionStringProcedure is the fully-qualified name of the DatabaseService's
	// GetConnectionString RPC.
	DatabaseServiceGetConnectionStringProcedure = "/dcloud.database.v1.DatabaseService/GetConnectionString"
	// DatabaseServiceGetOperationProcedure is the fully-qualified name of the DatabaseService's
	// GetOperation RPC.
	DatabaseServiceGetOperationProcedure = "/dcloud.database.v1.DatabaseService/GetOperation"
	// DatabaseServiceListSchemasProcedure is the fully-qualified name of the DatabaseService's
	// ListSchemas RPC.
	DatabaseServiceListSchemasProcedure = "/dcloud.database.v1.DatabaseService/ListSchemas"
	// DatabaseServiceCreateSchemaProcedure is the fully-qualified name of the DatabaseService's
	// CreateSchema RPC.
	DatabaseServiceCreateSchemaProcedure = "/dcloud.database.v1.DatabaseService/CreateSchema"
	// DatabaseServiceDeleteSchemaProcedure is the fully-qualified name of the DatabaseService's
	// DeleteSchema RPC.
	DatabaseServiceDeleteSchemaProcedure = "/dcloud.database.v1.DatabaseService/DeleteSchema"
	// DatabaseServiceListBackupsProcedure is the fully-qualified name of the DatabaseService's
	// ListBackups RPC.
	DatabaseServiceListBackupsProcedure = "/dcloud.database.v1.DatabaseService/ListBackups"
	// DatabaseServiceCreateBackupProcedure is the fully-qualified name of the DatabaseService's
	// CreateBackup RPC.
	DatabaseServiceCreateBackupProcedure = "/dcloud.database.v1.DatabaseService/CreateBackup"
	// DatabaseServiceDeleteBackupProcedure is the fully-qualified name of the DatabaseService's
	// DeleteBackup RPC.
	DatabaseServiceDeleteBackupProcedure = "/dcloud.database.v1.DatabaseService/DeleteBackup"
)

// DatabaseServiceClient is a client for the dcloud.database.v1.DatabaseService service.
type DatabaseServiceClient interface {
	Health(context.Context, *connect.Request[databasepb.HealthRequest]) (*connect.Response[databasepb.HealthResponse], error)
	ListDatabases(context.Context, *connect.Request[databasepb.ListDatabasesRequest]) (*connect.Response[databasepb.ListDatabasesResponse], error)
	CreateDatabase(context.Context, *connect.Request[databasepb.CreateDatabaseRequest]) (*connect.Response[databasepb.CreateDatabaseResponse], error)
	DeleteDatabase(context.Context, *connect.Request[databasepb.DeleteDatabaseRequest]) (*connect.Response[databasepb.DeleteDatabaseResponse], error)
	GetDatabase(context.Context, *connect.Request[databasepb.GetDatabaseRequest]) (*connect.Response[databasepb.GetDatabaseResponse], error)
	GetConnectionString(context.Context, *connect.Request[databasepb.GetConnectionStringRequest]) (*connect.Response[databasepb.GetConnectionStringResponse], error)
	GetOperation(context.Context, *connect.Request[databasepb.GetOperationRequest]) (*connect.Response[databasepb.GetOperationResponse], error)
	// Schema (logical database) management inside a DB instance.
	ListSchemas(context.Context, *connect.Request[databasepb.ListSchemasRequest]) (*connect.Response[databasepb.ListSchemasResponse], error)
	CreateSchema(context.Context, *connect.Request[databasepb.CreateSchemaRequest]) (*connect.Response[databasepb.CreateSchemaResponse], error)
	DeleteSchema(context.Context, *connect.Request[databasepb.DeleteSchemaRequest]) (*connect.Response[databasepb.DeleteSchemaResponse], error)
	// Backups
	ListBackups(context.Context, *connect.Request[databasepb.ListBackupsRequest]) (*connect.Response[databasepb.ListBackupsResponse], error)
	CreateBackup(context.Context, *connect.Request[databasepb.CreateBackupRequest]) (*connect.Response[databasepb.CreateBackupResponse], error)
	DeleteBackup(context.Context, *connect.Request[databasepb.DeleteBackupRequest]) (*connect.Response[databasepb.DeleteBackupResponse], error)
}

// NewDatabaseServiceClient constructs a client for the dcloud.database.v1.DatabaseService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDatabaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DatabaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	databaseServiceMethods := databasepb.File_database_proto.Services().ByName("DatabaseService").Methods()
	return &databaseServiceClient{
		health: connect.NewClient[databasepb.HealthRequest, databasepb.HealthResponse](
			httpClient,
			baseURL+DatabaseServiceHealthProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
		listDatabases: connect.NewClient[databasepb.ListDatabasesRequest, databasepb.ListDatabasesResponse](
			httpClient,
			baseURL+DatabaseServiceListDatabasesProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ListDatabases")),
			connect.WithClientOptions(opts...),
		),
		createDatabase: connect.NewClient[databasepb.CreateDatabaseRequest, databasepb.CreateDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceCreateDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CreateDatabase")),
			connect.WithClientOptions(opts...),
		),
		deleteDatabase: connect.NewClient[databasepb.DeleteDatabaseRequest, databasepb.DeleteDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceDeleteDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("DeleteDatabase")),
			connect.WithClientOptions(opts...),
		),
		getDatabase: connect.NewClient[databasepb.GetDatabaseRequest, databasepb.GetDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceGetDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetDatabase")),
			connect.WithClientOptions(opts...),
		),
		getConnectionString: connect.NewClient[databasepb.GetConnectionStringRequest, databasepb.GetConnectionStringResponse](
			httpClient,
			baseURL+DatabaseServiceGetConnectionStringProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetConnectionString")),
			connect.WithClientOptions(opts...),
		),
		getOperation: connect.NewClient[databasepb.GetOperationRequest, databasepb.GetOperationResponse](
			httpClient,
			baseURL+DatabaseServiceGetOperationProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetOperation")),
			connect.WithClientOptions(opts...),
		),
		listSchemas: connect.NewClient[databasepb.ListSchemasRequest, databasepb.ListSchemasResponse](
			httpClient,
			baseURL+DatabaseServiceListSchemasProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ListSchemas")),
			connect.WithClientOptions(opts...),
		),
		createSchema: connect.NewClient[databasepb.CreateSchemaRequest, databasepb.CreateSchemaResponse](
			httpClient,
			baseURL+DatabaseServiceCreateSchemaProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CreateSchema")),
			connect.WithClientOptions(opts...),
		),
		deleteSchema: connect.NewClient[databasepb.DeleteSchemaRequest, databasepb.DeleteSchemaResponse](
			httpClient,
			baseURL+DatabaseServiceDeleteSchemaProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("DeleteSchema")),
			connect.WithClientOptions(opts...),
		),
		listBackups: connect.NewClient[databasepb.ListBackupsRequest, databasepb.ListBackupsResponse](
			httpClient,
			baseURL+DatabaseServiceListBackupsProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ListBackups")),
			connect.WithClientOptions(opts...),
		),
		createBackup: connect.NewClient[databasepb.CreateBackupRequest, databasepb.CreateBackupResponse](
			httpClient,
			baseURL+DatabaseServiceCreateBackupProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CreateBackup")),
			connect.WithClientOptions(opts...),
		),
		deleteBackup: connect.NewClient[databasepb.DeleteBackupRequest, databasepb.DeleteBackupResponse](
			httpClient,
			baseURL+DatabaseServiceDeleteBackupProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("DeleteBackup")),
			connect.WithClientOptions(opts...),
		),
	}
}

// databaseServiceClient implements DatabaseServiceClient.
type databaseServiceClient struct {
	health              *connect.Client[databasepb.HealthRequest, databasepb.HealthResponse]
	listDatabases       *connect.Client[databasepb.ListDatabasesRequest, databasepb.ListDatabasesResponse]
	createDatabase      *connect.Client[databasepb.CreateDatabaseRequest, databasepb.CreateDatabaseResponse]
	deleteDatabase      *connect.Client[databasepb.DeleteDatabaseRequest, databasepb.DeleteDatabaseResponse]
	getDatabase         *connect.Client[databasepb.GetDatabaseRequest, databasepb.GetDatabaseResponse]
	getConnectionString *connect.Client[databasepb.GetConnectionStringRequest, databasepb.GetConnectionStringResponse]
	getOperation        *connect.Client[databasepb.GetOperationRequest, databasepb.GetOperationResponse]
	listSchemas         *connect.Client[databasepb.ListSchemasRequest, databasepb.ListSchemasResponse]
	createSchema        *connect.Client[databasepb.CreateSchemaRequest, databasepb.CreateSchemaResponse]
	deleteSchema        *connect.Client[databasepb.DeleteSchemaRequest, databasepb.DeleteSchemaResponse]
	listBackups         *connect.Client[databasepb.ListBackupsRequest, databasepb.ListBackupsResponse]
	createBackup        *connect.Client[databasepb.CreateBackupRequest, databasepb.CreateBackupResponse]
	deleteBackup        *connect.Client[databasepb.DeleteBackupRequest, databasepb.DeleteBackupResponse]
}

// Health calls dcloud.database.v1.DatabaseService.Health.
func (c *databaseServiceClient) Health(ctx context.Context, req *connect.Request[databasepb.HealthRequest]) (*connect.Response[databasepb.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// ListDatabases calls dcloud.database.v1.DatabaseService.ListDatabases.
func (c *databaseServiceClient) ListDatabases(ctx context.Context, req *connect.Request[databasepb.ListDatabasesRequest]) (*connect.Response[databasepb.ListDatabasesResponse], error) {
	return c.listDatabases.CallUnary(ctx, req)
}

// CreateDatabase calls dcloud.database.v1.DatabaseService.CreateDatabase.
func (c *databaseServiceClient) CreateDatabase(ctx context.Context, req *connect.Request[databasepb.CreateDatabaseRequest]) (*connect.Response[databasepb.CreateDatabaseResponse], error) {
	return c.createDatabase.CallUnary(ctx, req)
}

// DeleteDatabase calls dcloud.database.v1.DatabaseService.DeleteDatabase.
func (c *databaseServiceClient) DeleteDatabase(ctx context.Context, req *connect.Request[databasepb.DeleteDatabaseRequest]) (*connect.Response[databasepb.DeleteDatabaseResponse], error) {
	return c.deleteDatabase.CallUnary(ctx, req)
}

// GetDatabase calls dcloud.database.v1.DatabaseService.GetDatabase.
func (c *databaseServiceClient) GetDatabase(ctx context.Context, req *connect.Request[databasepb.GetDatabaseRequest]) (*connect.Response[databasepb.GetDatabaseResponse], error) {
	return c.getDatabase.CallUnary(ctx, req)
}

// GetConnectionString calls dcloud.database.v1.DatabaseService.GetConnectionString.
func (c *databaseServiceClient) GetConnectionString(ctx context.Context, req *connect.Request[databasepb.GetConnectionStringRequest]) (*connect.Response[databasepb.GetConnectionStringResponse], error) {
	return c.getConnectionString.CallUnary(ctx, req)
}

// GetOperation calls dcloud.database.v1.DatabaseService.GetOperation.
func (c *databaseServiceClient) GetOperation(ctx context.Context, req *connect.Request[databasepb.GetOperationRequest]) (*connect.Response[databasepb.GetOperationResponse], error) {
	return c.getOperation.CallUnary(ctx, req)
}

// ListSchemas calls dcloud.database.v1.DatabaseService.ListSchemas.
func (c *databaseServiceClient) ListSchemas(ctx context.Context, req *connect.Request[databasepb.ListSchemasRequest]) (*connect.Response[databasepb.ListSchemasResponse], error) {
	return c.listSchemas.CallUnary(ctx, req)
}

// CreateSchema calls dcloud.database.v1.DatabaseService.CreateSchema.
func (c *databaseServiceClient) CreateSchema(ctx context.Context, req *connect.Request[databasepb.CreateSchemaRequest]) (*connect.Response[databasepb.CreateSchemaResponse], error) {
	return c.createSchema.CallUnary(ctx, req)
}

// DeleteSchema calls dcloud.database.v1.DatabaseService.DeleteSchema.
func (c *databaseServiceClient) DeleteSchema(ctx context.Context, req *connect.Request[databasepb.DeleteSchemaRequest]) (*connect.Response[databasepb.DeleteSchemaResponse], error) {
	return c.deleteSchema.CallUnary(ctx, req)
}

// ListBackups calls dcloud.database.v1.DatabaseService.ListBackups.
func (c *databaseServiceClient) ListBackups(ctx context.Context, req *connect.Request[databasepb.ListBackupsRequest]) (*connect.Response[databasepb.ListBackupsResponse], error) {
	return c.listBackups.CallUnary(ctx, req)
}

// CreateBackup calls dcloud.database.v1.DatabaseService.CreateBackup.
func (c *databaseServiceClient) CreateBackup(ctx context.Context, req *connect.Request[databasepb.CreateBackupRequest]) (*connect.Response[databasepb.CreateBackupResponse], error) {
	return c.createBackup.CallUnary(ctx, req)
}

// DeleteBackup calls dcloud.database.v1.DatabaseService.DeleteBackup.
func (c *databaseServiceClient) DeleteBackup(ctx context.Context, req *connect.Request[databasepb.DeleteBackupRequest]) (*connect.Response[databasepb.DeleteBackupResponse], error) {
	return c.deleteBackup.CallUnary(ctx, req)
}

// DatabaseServiceHandler is an implementation of the dcloud.database.v1.DatabaseService service.
type DatabaseServiceHandler interface {
	Health(context.Context, *connect.Request[databasepb.HealthRequest]) (*connect.Response[databasepb.HealthResponse], error)
	ListDatabases(context.Context, *connect.Request[databasepb.ListDatabasesRequest]) (*connect.Response[databasepb.ListDatabasesResponse], error)
	CreateDatabase(context.Context, *connect.Request[databasepb.CreateDatabaseRequest]) (*connect.Response[databasepb.CreateDatabaseResponse], error)
	DeleteDatabase(context.Context, *connect.Request[databasepb.DeleteDatabaseRequest]) (*connect.Response[databasepb.DeleteDatabaseResponse], error)
	GetDatabase(context.Context, *connect.Request[databasepb.GetDatabaseRequest]) (*connect.Response[databasepb.GetDatabaseResponse], error)
	GetConnectionString(context.Context, *connect.Request[databasepb.GetConnectionStringRequest]) (*connect.Response[databasepb.GetConnectionStringResponse], error)
	GetOperation(context.Context, *connect.Request[databasepb.GetOperationRequest]) (*connect.Response[databasepb.GetOperationResponse], error)
	// Schema (logical database) management inside a DB instance.
	ListSchemas(context.Context, *connect.Request[databasepb.ListSchemasRequest]) (*connect.Response[databasepb.ListSchemasResponse], error)
	CreateSchema(context.Context, *connect.Request[databasepb.CreateSchemaRequest]) (*connect.Response[databasepb.CreateSchemaResponse], error)
	DeleteSchema(context.Context, *connect.Request[databasepb.DeleteSchemaRequest]) (*connect.Response[databasepb.DeleteSchemaResponse], error)
	// Backups
	ListBackups(context.Context, *connect.Request[databasepb.ListBackupsRequest]) (*connect.Response[databasepb.ListBackupsResponse], error)
	CreateBackup(context.Context, *connect.Request[databasepb.CreateBackupRequest]) (*connect.Response[databasepb.CreateBackupResponse], error)
	DeleteBackup(context.Context, *connect.Request[databasepb.DeleteBackupRequest]) (*connect.Response[databasepb.DeleteBackupResponse], error)
}

// NewDatabaseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDatabaseServiceHandler(svc DatabaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	databaseServiceMethods := databasepb.File_database_proto.Services().ByName("DatabaseService").Methods()
	databaseServiceHealthHandler := connect.NewUnaryHandler(
		DatabaseServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(databaseServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceListDatabasesHandler := connect.NewUnaryHandler(
		DatabaseServiceListDatabasesProcedure,
		svc.ListDatabases,
		connect.WithSchema(databaseServiceMethods.ByName("ListDatabases")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCreateDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceCreateDatabaseProcedure,
		svc.CreateDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("CreateDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceDeleteDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceDeleteDatabaseProcedure,
		svc.DeleteDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("DeleteDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceGetDatabaseProcedure,
		svc.GetDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("GetDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetConnectionStringHandler := connect.NewUnaryHandler(
		DatabaseServiceGetConnectionStringProcedure,
		svc.GetConnectionString,
		connect.WithSchema(databaseServiceMethods.ByName("GetConnectionString")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetOperationHandler := connect.NewUnaryHandler(
		DatabaseServiceGetOperationProcedure,
		svc.GetOperation,
		connect.WithSchema(databaseServiceMethods.ByName("GetOperation")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceListSchemasHandler := connect.NewUnaryHandler(
		DatabaseServiceListSchemasProcedure,
		svc.ListSchemas,
		connect.WithSchema(databaseServiceMethods.ByName("ListSchemas")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCreateSchemaHandler := connect.NewUnaryHandler(
		DatabaseServiceCreateSchemaProcedure,
		svc.CreateSchema,
		connect.WithSchema(databaseServiceMethods.ByName("CreateSchema")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceDeleteSchemaHandler := connect.NewUnaryHandler(
		DatabaseServiceDeleteSchemaProcedure,
		svc.DeleteSchema,
		connect.WithSchema(databaseServiceMethods.ByName("DeleteSchema")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceListBackupsHandler := connect.NewUnaryHandler(
		DatabaseServiceListBackupsProcedure,
		svc.ListBackups,
		connect.WithSchema(databaseServiceMethods.ByName("ListBackups")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCreateBackupHandler := connect.NewUnaryHandler(
		DatabaseServiceCreateBackupProcedure,
		svc.CreateBackup,
		connect.WithSchema(databaseServiceMethods.ByName("CreateBackup")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceDeleteBackupHandler := connect.NewUnaryHandler(
		DatabaseServiceDeleteBackupProcedure,
		svc.DeleteBackup,
		connect.WithSchema(databaseServiceMethods.ByName("DeleteBackup")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dcloud.database.v1.DatabaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DatabaseServiceHealthProcedure:
			databaseServiceHealthHandler.ServeHTTP(w, r)
		case DatabaseServiceListDatabasesProcedure:
			databaseServiceListDatabasesHandler.ServeHTTP(w, r)
		case DatabaseServiceCreateDatabaseProcedure:
			databaseServiceCreateDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceDeleteDatabaseProcedure:
			databaseServiceDeleteDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceGetDatabaseProcedure:
			databaseServiceGetDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceGetConnectionStringProcedure:
			databaseServiceGetConnectionStringHandler.ServeHTTP(w, r)
		case DatabaseServiceGetOperationProcedure:
			databaseServiceGetOperationHandler.ServeHTTP(w, r)
		case DatabaseServiceListSchemasProcedure:
			databaseServiceListSchemasHandler.ServeHTTP(w, r)
		case DatabaseServiceCreateSchemaProcedure:
			databaseServiceCreateSchemaHandler.ServeHTTP(w, r)
		case DatabaseServiceDeleteSchemaProcedure:
			databaseServiceDeleteSchemaHandler.ServeHTTP(w, r)
		case DatabaseServiceListBackupsProcedure:
			databaseServiceListBackupsHandler.ServeHTTP(w, r)
		case DatabaseServiceCreateBackupProcedure:
			databaseServiceCreateBackupHandler.ServeHTTP(w, r)
		case DatabaseServiceDeleteBackupProcedure:
			databaseServiceDeleteBackupHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDatabaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDatabaseServiceHandler struct{}

func (UnimplementedDatabaseServiceHandler) Health(context.Context, *connect.Request[databasepb.HealthRequest]) (*connect.Response[databasepb.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.Health is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ListDatabases(context.Context, *connect.Request[databasepb.ListDatabasesRequest]) (*connect.Response[databasepb.ListDatabasesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.ListDatabases is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) CreateDatabase(context.Context, *connect.Request[databasepb.CreateDatabaseRequest]) (*connect.Response[databasepb.CreateDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.CreateDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) DeleteDatabase(context.Context, *connect.Request[databasepb.DeleteDatabaseRequest]) (*connect.Response[databasepb.DeleteDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.DeleteDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetDatabase(context.Context, *connect.Request[databasepb.GetDatabaseRequest]) (*connect.Response[databasepb.GetDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.GetDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetConnectionString(context.Context, *connect.Request[databasepb.GetConnectionStringRequest]) (*connect.Response[databasepb.GetConnectionStringResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.GetConnectionString is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetOperation(context.Context, *connect.Request[databasepb.GetOperationRequest]) (*connect.Response[databasepb.GetOperationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.GetOperation is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ListSchemas(context.Context, *connect.Request[databasepb.ListSchemasRequest]) (*connect.Response[databasepb.ListSchemasResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.ListSchemas is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) CreateSchema(context.Context, *connect.Request[databasepb.CreateSchemaRequest]) (*connect.Response[databasepb.CreateSchemaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.CreateSchema is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) DeleteSchema(context.Context, *connect.Request[databasepb.DeleteSchemaRequest]) (*connect.Response[databasepb.DeleteSchemaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.DeleteSchema is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ListBackups(context.Context, *connect.Request[databasepb.ListBackupsRequest]) (*connect.Response[databasepb.ListBackupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.ListBackups is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) CreateBackup(context.Context, *connect.Request[databasepb.CreateBackupRequest]) (*connect.Response[databasepb.CreateBackupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.CreateBackup is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) DeleteBackup(context.Context, *connect.Request[databasepb.DeleteBackupRequest]) (*connect.Response[databasepb.DeleteBackupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.database.v1.DatabaseService.DeleteBackup is not implemented"))
}
