apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/dcloud.git
    targetRevision: HEAD
    path: charts/knative-config
    helm:
      releaseName: knative-config
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
