apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: net-istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/knative/net-istio.git
    targetRevision: knative-v1.22.0
    path: config
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
