// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dbaas.proto

package dbaaspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_dbaas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_dbaas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Cpu           string                 `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       string                 `protobuf:"bytes,6,opt,name=storage,proto3" json:"storage,omitempty"`
	Ready         bool                   `protobuf:"varint,7,opt,name=ready,proto3" json:"ready,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ProjectId     string                 `protobuf:"bytes,10,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_dbaas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{2}
}

func (x *Database) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Database) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Database) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Database) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *Database) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *Database) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *Database) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Database) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Database) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Database) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListDatabasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesRequest) Reset() {
	*x = ListDatabasesRequest{}
	mi := &file_dbaas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesRequest) ProtoMessage() {}

func (x *ListDatabasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesRequest.ProtoReflect.Descriptor instead.
func (*ListDatabasesRequest) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{3}
}

func (x *ListDatabasesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListDatabasesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListDatabasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Databases     []*Database            `protobuf:"bytes,3,rep,name=databases,proto3" json:"databases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesResponse) Reset() {
	*x = ListDatabasesResponse{}
	mi := &file_dbaas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesResponse) ProtoMessage() {}

func (x *ListDatabasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesResponse.ProtoReflect.Descriptor instead.
func (*ListDatabasesResponse) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{4}
}

func (x *ListDatabasesResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListDatabasesResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListDatabasesResponse) GetDatabases() []*Database {
	if x != nil {
		return x.Databases
	}
	return nil
}

type CreateDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Cpu           string                 `protobuf:"bytes,6,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,7,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       string                 `protobuf:"bytes,8,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseRequest) Reset() {
	*x = CreateDatabaseRequest{}
	mi := &file_dbaas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseRequest) ProtoMessage() {}

func (x *CreateDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseRequest.ProtoReflect.Descriptor instead.
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDatabaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateDatabaseRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDatabaseRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateDatabaseRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateDatabaseRequest) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *CreateDatabaseRequest) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *CreateDatabaseRequest) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

type CreateDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Database              `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseResponse) Reset() {
	*x = CreateDatabaseResponse{}
	mi := &file_dbaas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseResponse) ProtoMessage() {}

func (x *CreateDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseResponse.ProtoReflect.Descriptor instead.
func (*CreateDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDatabaseResponse) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

type DeleteDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatabaseRequest) Reset() {
	*x = DeleteDatabaseRequest{}
	mi := &file_dbaas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatabaseRequest) ProtoMessage() {}

func (x *DeleteDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatabaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDatabaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteDatabaseRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatabaseResponse) Reset() {
	*x = DeleteDatabaseResponse{}
	mi := &file_dbaas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatabaseResponse) ProtoMessage() {}

func (x *DeleteDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatabaseResponse.ProtoReflect.Descriptor instead.
func (*DeleteDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDatabaseResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseRequest) Reset() {
	*x = GetDatabaseRequest{}
	mi := &file_dbaas_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseRequest) ProtoMessage() {}

func (x *GetDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseRequest.ProtoReflect.Descriptor instead.
func (*GetDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{9}
}

func (x *GetDatabaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDatabaseRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Database              `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseResponse) Reset() {
	*x = GetDatabaseResponse{}
	mi := &file_dbaas_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseResponse) ProtoMessage() {}

func (x *GetDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseResponse.ProtoReflect.Descriptor instead.
func (*GetDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{10}
}

func (x *GetDatabaseResponse) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

type GetConnectionStringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionStringRequest) Reset() {
	*x = GetConnectionStringRequest{}
	mi := &file_dbaas_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStringRequest) ProtoMessage() {}

func (x *GetConnectionStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStringRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionStringRequest) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{11}
}

func (x *GetConnectionStringRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetConnectionStringRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetConnectionStringRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetConnectionStringResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectionString string                 `protobuf:"bytes,1,opt,name=connection_string,json=connectionString,proto3" json:"connection_string,omitempty"`
	Host             string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port             string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Username         string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password         string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	DatabaseName     string                 `protobuf:"bytes,6,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetConnectionStringResponse) Reset() {
	*x = GetConnectionStringResponse{}
	mi := &file_dbaas_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStringResponse) ProtoMessage() {}

func (x *GetConnectionStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStringResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionStringResponse) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{12}
}

func (x *GetConnectionStringResponse) GetConnectionString() string {
	if x != nil {
		return x.ConnectionString
	}
	return ""
}

func (x *GetConnectionStringResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetConnectionStringResponse) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *GetConnectionStringResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetConnectionStringResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetConnectionStringResponse) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_dbaas_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{13}
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_dbaas_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbaas_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_dbaas_proto_rawDescGZIP(), []int{14}
}

func (x *GetOperationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetOperationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOperationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_dbaas_proto protoreflect.FileDescriptor

const file_dbaas_proto_rawDesc = "" +
	"\n" +
	"\vdbaas.proto\x12\x0fdcloud.dbaas.v1\"\x0f\n" +
	"\rHealthRequest\"`\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"\xfc\x01\n" +
	"\bDatabase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\tR\x06memory\x12\x18\n" +
	"\astorage\x18\x06 \x01(\tR\astorage\x12\x14\n" +
	"\x05ready\x18\a \x01(\bR\x05ready\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"project_id\x18\n" +
	" \x01(\tR\tprojectId\"N\n" +
	"\x14ListDatabasesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\x88\x01\n" +
	"\x15ListDatabasesResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x127\n" +
	"\tdatabases\x18\x03 \x03(\v2\x19.dcloud.dbaas.v1.DatabaseR\tdatabases\"\xd5\x01\n" +
	"\x15CreateDatabaseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x10\n" +
	"\x03cpu\x18\x06 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\a \x01(\tR\x06memory\x12\x18\n" +
	"\astorage\x18\b \x01(\tR\astorage\"O\n" +
	"\x16CreateDatabaseResponse\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.dcloud.dbaas.v1.DatabaseR\bdatabase\"c\n" +
	"\x15DeleteDatabaseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\";\n" +
	"\x16DeleteDatabaseResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"`\n" +
	"\x12GetDatabaseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"L\n" +
	"\x13GetDatabaseResponse\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.dcloud.dbaas.v1.DatabaseR\bdatabase\"h\n" +
	"\x1aGetConnectionStringRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xcf\x01\n" +
	"\x1bGetConnectionStringResponse\x12+\n" +
	"\x11connection_string\x18\x01 \x01(\tR\x10connectionString\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12#\n" +
	"\rdatabase_name\x18\x06 \x01(\tR\fdatabaseName\"8\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"g\n" +
	"\x14GetOperationResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xab\x05\n" +
	"\x0fDatabaseService\x12I\n" +
	"\x06Health\x12\x1e.dcloud.dbaas.v1.HealthRequest\x1a\x1f.dcloud.dbaas.v1.HealthResponse\x12^\n" +
	"\rListDatabases\x12%.dcloud.dbaas.v1.ListDatabasesRequest\x1a&.dcloud.dbaas.v1.ListDatabasesResponse\x12a\n" +
	"\x0eCreateDatabase\x12&.dcloud.dbaas.v1.CreateDatabaseRequest\x1a'.dcloud.dbaas.v1.CreateDatabaseResponse\x12a\n" +
	"\x0eDeleteDatabase\x12&.dcloud.dbaas.v1.DeleteDatabaseRequest\x1a'.dcloud.dbaas.v1.DeleteDatabaseResponse\x12X\n" +
	"\vGetDatabase\x12#.dcloud.dbaas.v1.GetDatabaseRequest\x1a$.dcloud.dbaas.v1.GetDatabaseResponse\x12p\n" +
	"\x13GetConnectionString\x12+.dcloud.dbaas.v1.GetConnectionStringRequest\x1a,.dcloud.dbaas.v1.GetConnectionStringResponse\x12[\n" +
	"\fGetOperation\x12$.dcloud.dbaas.v1.GetOperationRequest\x1a%.dcloud.dbaas.v1.GetOperationResponseB<Z:github.com/daigo-suhara/dcloud/internal/pb/dbaaspb;dbaaspbb\x06proto3"

var (
	file_dbaas_proto_rawDescOnce sync.Once
	file_dbaas_proto_rawDescData []byte
)

func file_dbaas_proto_rawDescGZIP() []byte {
	file_dbaas_proto_rawDescOnce.Do(func() {
		file_dbaas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dbaas_proto_rawDesc), len(file_dbaas_proto_rawDesc)))
	})
	return file_dbaas_proto_rawDescData
}

var file_dbaas_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_dbaas_proto_goTypes = []any{
	(*HealthRequest)(nil),               // 0: dcloud.dbaas.v1.HealthRequest
	(*HealthResponse)(nil),              // 1: dcloud.dbaas.v1.HealthResponse
	(*Database)(nil),                    // 2: dcloud.dbaas.v1.Database
	(*ListDatabasesRequest)(nil),        // 3: dcloud.dbaas.v1.ListDatabasesRequest
	(*ListDatabasesResponse)(nil),       // 4: dcloud.dbaas.v1.ListDatabasesResponse
	(*CreateDatabaseRequest)(nil),       // 5: dcloud.dbaas.v1.CreateDatabaseRequest
	(*CreateDatabaseResponse)(nil),      // 6: dcloud.dbaas.v1.CreateDatabaseResponse
	(*DeleteDatabaseRequest)(nil),       // 7: dcloud.dbaas.v1.DeleteDatabaseRequest
	(*DeleteDatabaseResponse)(nil),      // 8: dcloud.dbaas.v1.DeleteDatabaseResponse
	(*GetDatabaseRequest)(nil),          // 9: dcloud.dbaas.v1.GetDatabaseRequest
	(*GetDatabaseResponse)(nil),         // 10: dcloud.dbaas.v1.GetDatabaseResponse
	(*GetConnectionStringRequest)(nil),  // 11: dcloud.dbaas.v1.GetConnectionStringRequest
	(*GetConnectionStringResponse)(nil), // 12: dcloud.dbaas.v1.GetConnectionStringResponse
	(*GetOperationRequest)(nil),         // 13: dcloud.dbaas.v1.GetOperationRequest
	(*GetOperationResponse)(nil),        // 14: dcloud.dbaas.v1.GetOperationResponse
}
var file_dbaas_proto_depIdxs = []int32{
	2,  // 0: dcloud.dbaas.v1.ListDatabasesResponse.databases:type_name -> dcloud.dbaas.v1.Database
	2,  // 1: dcloud.dbaas.v1.CreateDatabaseResponse.database:type_name -> dcloud.dbaas.v1.Database
	2,  // 2: dcloud.dbaas.v1.GetDatabaseResponse.database:type_name -> dcloud.dbaas.v1.Database
	0,  // 3: dcloud.dbaas.v1.DatabaseService.Health:input_type -> dcloud.dbaas.v1.HealthRequest
	3,  // 4: dcloud.dbaas.v1.DatabaseService.ListDatabases:input_type -> dcloud.dbaas.v1.ListDatabasesRequest
	5,  // 5: dcloud.dbaas.v1.DatabaseService.CreateDatabase:input_type -> dcloud.dbaas.v1.CreateDatabaseRequest
	7,  // 6: dcloud.dbaas.v1.DatabaseService.DeleteDatabase:input_type -> dcloud.dbaas.v1.DeleteDatabaseRequest
	9,  // 7: dcloud.dbaas.v1.DatabaseService.GetDatabase:input_type -> dcloud.dbaas.v1.GetDatabaseRequest
	11, // 8: dcloud.dbaas.v1.DatabaseService.GetConnectionString:input_type -> dcloud.dbaas.v1.GetConnectionStringRequest
	13, // 9: dcloud.dbaas.v1.DatabaseService.GetOperation:input_type -> dcloud.dbaas.v1.GetOperationRequest
	1,  // 10: dcloud.dbaas.v1.DatabaseService.Health:output_type -> dcloud.dbaas.v1.HealthResponse
	4,  // 11: dcloud.dbaas.v1.DatabaseService.ListDatabases:output_type -> dcloud.dbaas.v1.ListDatabasesResponse
	6,  // 12: dcloud.dbaas.v1.DatabaseService.CreateDatabase:output_type -> dcloud.dbaas.v1.CreateDatabaseResponse
	8,  // 13: dcloud.dbaas.v1.DatabaseService.DeleteDatabase:output_type -> dcloud.dbaas.v1.DeleteDatabaseResponse
	10, // 14: dcloud.dbaas.v1.DatabaseService.GetDatabase:output_type -> dcloud.dbaas.v1.GetDatabaseResponse
	12, // 15: dcloud.dbaas.v1.DatabaseService.GetConnectionString:output_type -> dcloud.dbaas.v1.GetConnectionStringResponse
	14, // 16: dcloud.dbaas.v1.DatabaseService.GetOperation:output_type -> dcloud.dbaas.v1.GetOperationResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_dbaas_proto_init() }
func file_dbaas_proto_init() {
	if File_dbaas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dbaas_proto_rawDesc), len(file_dbaas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dbaas_proto_goTypes,
		DependencyIndexes: file_dbaas_proto_depIdxs,
		MessageInfos:      file_dbaas_proto_msgTypes,
	}.Build()
	File_dbaas_proto = out.File
	file_dbaas_proto_goTypes = nil
	file_dbaas_proto_depIdxs = nil
}
