// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: identity.proto

package identitypbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	identitypb "github.com/daigo-suhara/dcloud/internal/pb/identitypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IdentityServiceName is the fully-qualified name of the IdentityService service.
	IdentityServiceName = "dcloud.identity.v1.IdentityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IdentityServiceHealthProcedure is the fully-qualified name of the IdentityService's Health RPC.
	IdentityServiceHealthProcedure = "/dcloud.identity.v1.IdentityService/Health"
	// IdentityServiceRegisterProcedure is the fully-qualified name of the IdentityService's Register
	// RPC.
	IdentityServiceRegisterProcedure = "/dcloud.identity.v1.IdentityService/Register"
	// IdentityServiceLoginProcedure is the fully-qualified name of the IdentityService's Login RPC.
	IdentityServiceLoginProcedure = "/dcloud.identity.v1.IdentityService/Login"
	// IdentityServiceMeProcedure is the fully-qualified name of the IdentityService's Me RPC.
	IdentityServiceMeProcedure = "/dcloud.identity.v1.IdentityService/Me"
	// IdentityServiceLogoutProcedure is the fully-qualified name of the IdentityService's Logout RPC.
	IdentityServiceLogoutProcedure = "/dcloud.identity.v1.IdentityService/Logout"
)

// IdentityServiceClient is a client for the dcloud.identity.v1.IdentityService service.
type IdentityServiceClient interface {
	Health(context.Context, *connect.Request[identitypb.HealthRequest]) (*connect.Response[identitypb.HealthResponse], error)
	Register(context.Context, *connect.Request[identitypb.RegisterRequest]) (*connect.Response[identitypb.RegisterResponse], error)
	Login(context.Context, *connect.Request[identitypb.LoginRequest]) (*connect.Response[identitypb.LoginResponse], error)
	Me(context.Context, *connect.Request[identitypb.MeRequest]) (*connect.Response[identitypb.MeResponse], error)
	Logout(context.Context, *connect.Request[identitypb.LogoutRequest]) (*connect.Response[identitypb.LogoutResponse], error)
}

// NewIdentityServiceClient constructs a client for the dcloud.identity.v1.IdentityService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIdentityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IdentityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	identityServiceMethods := identitypb.File_identity_proto.Services().ByName("IdentityService").Methods()
	return &identityServiceClient{
		health: connect.NewClient[identitypb.HealthRequest, identitypb.HealthResponse](
			httpClient,
			baseURL+IdentityServiceHealthProcedure,
			connect.WithSchema(identityServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
		register: connect.NewClient[identitypb.RegisterRequest, identitypb.RegisterResponse](
			httpClient,
			baseURL+IdentityServiceRegisterProcedure,
			connect.WithSchema(identityServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[identitypb.LoginRequest, identitypb.LoginResponse](
			httpClient,
			baseURL+IdentityServiceLoginProcedure,
			connect.WithSchema(identityServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		me: connect.NewClient[identitypb.MeRequest, identitypb.MeResponse](
			httpClient,
			baseURL+IdentityServiceMeProcedure,
			connect.WithSchema(identityServiceMethods.ByName("Me")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[identitypb.LogoutRequest, identitypb.LogoutResponse](
			httpClient,
			baseURL+IdentityServiceLogoutProcedure,
			connect.WithSchema(identityServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
	}
}

// identityServiceClient implements IdentityServiceClient.
type identityServiceClient struct {
	health   *connect.Client[identitypb.HealthRequest, identitypb.HealthResponse]
	register *connect.Client[identitypb.RegisterRequest, identitypb.RegisterResponse]
	login    *connect.Client[identitypb.LoginRequest, identitypb.LoginResponse]
	me       *connect.Client[identitypb.MeRequest, identitypb.MeResponse]
	logout   *connect.Client[identitypb.LogoutRequest, identitypb.LogoutResponse]
}

// Health calls dcloud.identity.v1.IdentityService.Health.
func (c *identityServiceClient) Health(ctx context.Context, req *connect.Request[identitypb.HealthRequest]) (*connect.Response[identitypb.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// Register calls dcloud.identity.v1.IdentityService.Register.
func (c *identityServiceClient) Register(ctx context.Context, req *connect.Request[identitypb.RegisterRequest]) (*connect.Response[identitypb.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Login calls dcloud.identity.v1.IdentityService.Login.
func (c *identityServiceClient) Login(ctx context.Context, req *connect.Request[identitypb.LoginRequest]) (*connect.Response[identitypb.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// Me calls dcloud.identity.v1.IdentityService.Me.
func (c *identityServiceClient) Me(ctx context.Context, req *connect.Request[identitypb.MeRequest]) (*connect.Response[identitypb.MeResponse], error) {
	return c.me.CallUnary(ctx, req)
}

// Logout calls dcloud.identity.v1.IdentityService.Logout.
func (c *identityServiceClient) Logout(ctx context.Context, req *connect.Request[identitypb.LogoutRequest]) (*connect.Response[identitypb.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// IdentityServiceHandler is an implementation of the dcloud.identity.v1.IdentityService service.
type IdentityServiceHandler interface {
	Health(context.Context, *connect.Request[identitypb.HealthRequest]) (*connect.Response[identitypb.HealthResponse], error)
	Register(context.Context, *connect.Request[identitypb.RegisterRequest]) (*connect.Response[identitypb.RegisterResponse], error)
	Login(context.Context, *connect.Request[identitypb.LoginRequest]) (*connect.Response[identitypb.LoginResponse], error)
	Me(context.Context, *connect.Request[identitypb.MeRequest]) (*connect.Response[identitypb.MeResponse], error)
	Logout(context.Context, *connect.Request[identitypb.LogoutRequest]) (*connect.Response[identitypb.LogoutResponse], error)
}

// NewIdentityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIdentityServiceHandler(svc IdentityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	identityServiceMethods := identitypb.File_identity_proto.Services().ByName("IdentityService").Methods()
	identityServiceHealthHandler := connect.NewUnaryHandler(
		IdentityServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(identityServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceRegisterHandler := connect.NewUnaryHandler(
		IdentityServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(identityServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceLoginHandler := connect.NewUnaryHandler(
		IdentityServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(identityServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceMeHandler := connect.NewUnaryHandler(
		IdentityServiceMeProcedure,
		svc.Me,
		connect.WithSchema(identityServiceMethods.ByName("Me")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceLogoutHandler := connect.NewUnaryHandler(
		IdentityServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(identityServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dcloud.identity.v1.IdentityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IdentityServiceHealthProcedure:
			identityServiceHealthHandler.ServeHTTP(w, r)
		case IdentityServiceRegisterProcedure:
			identityServiceRegisterHandler.ServeHTTP(w, r)
		case IdentityServiceLoginProcedure:
			identityServiceLoginHandler.ServeHTTP(w, r)
		case IdentityServiceMeProcedure:
			identityServiceMeHandler.ServeHTTP(w, r)
		case IdentityServiceLogoutProcedure:
			identityServiceLogoutHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIdentityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIdentityServiceHandler struct{}

func (UnimplementedIdentityServiceHandler) Health(context.Context, *connect.Request[identitypb.HealthRequest]) (*connect.Response[identitypb.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.identity.v1.IdentityService.Health is not implemented"))
}

func (UnimplementedIdentityServiceHandler) Register(context.Context, *connect.Request[identitypb.RegisterRequest]) (*connect.Response[identitypb.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.identity.v1.IdentityService.Register is not implemented"))
}

func (UnimplementedIdentityServiceHandler) Login(context.Context, *connect.Request[identitypb.LoginRequest]) (*connect.Response[identitypb.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.identity.v1.IdentityService.Login is not implemented"))
}

func (UnimplementedIdentityServiceHandler) Me(context.Context, *connect.Request[identitypb.MeRequest]) (*connect.Response[identitypb.MeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.identity.v1.IdentityService.Me is not implemented"))
}

func (UnimplementedIdentityServiceHandler) Logout(context.Context, *connect.Request[identitypb.LogoutRequest]) (*connect.Response[identitypb.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.identity.v1.IdentityService.Logout is not implemented"))
}
