// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: project.proto

package projectpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	projectpb "github.com/daigo-suhara/dcloud/internal/pb/projectpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProjectServiceName is the fully-qualified name of the ProjectService service.
	ProjectServiceName = "dcloud.project.v1.ProjectService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProjectServiceHealthProcedure is the fully-qualified name of the ProjectService's Health RPC.
	ProjectServiceHealthProcedure = "/dcloud.project.v1.ProjectService/Health"
	// ProjectServicePlatformProcedure is the fully-qualified name of the ProjectService's Platform RPC.
	ProjectServicePlatformProcedure = "/dcloud.project.v1.ProjectService/Platform"
	// ProjectServiceListProjectsProcedure is the fully-qualified name of the ProjectService's
	// ListProjects RPC.
	ProjectServiceListProjectsProcedure = "/dcloud.project.v1.ProjectService/ListProjects"
	// ProjectServiceCreateProjectProcedure is the fully-qualified name of the ProjectService's
	// CreateProject RPC.
	ProjectServiceCreateProjectProcedure = "/dcloud.project.v1.ProjectService/CreateProject"
	// ProjectServiceDeleteProjectProcedure is the fully-qualified name of the ProjectService's
	// DeleteProject RPC.
	ProjectServiceDeleteProjectProcedure = "/dcloud.project.v1.ProjectService/DeleteProject"
	// ProjectServiceIsProjectDeletingProcedure is the fully-qualified name of the ProjectService's
	// IsProjectDeleting RPC.
	ProjectServiceIsProjectDeletingProcedure = "/dcloud.project.v1.ProjectService/IsProjectDeleting"
	// ProjectServiceProjectExistsProcedure is the fully-qualified name of the ProjectService's
	// ProjectExists RPC.
	ProjectServiceProjectExistsProcedure = "/dcloud.project.v1.ProjectService/ProjectExists"
	// ProjectServiceGetProjectRepositoryProcedure is the fully-qualified name of the ProjectService's
	// GetProjectRepository RPC.
	ProjectServiceGetProjectRepositoryProcedure = "/dcloud.project.v1.ProjectService/GetProjectRepository"
	// ProjectServiceUpsertProjectRepositoryProcedure is the fully-qualified name of the
	// ProjectService's UpsertProjectRepository RPC.
	ProjectServiceUpsertProjectRepositoryProcedure = "/dcloud.project.v1.ProjectService/UpsertProjectRepository"
	// ProjectServiceCreateProjectDeleteOperationProcedure is the fully-qualified name of the
	// ProjectService's CreateProjectDeleteOperation RPC.
	ProjectServiceCreateProjectDeleteOperationProcedure = "/dcloud.project.v1.ProjectService/CreateProjectDeleteOperation"
)

// ProjectServiceClient is a client for the dcloud.project.v1.ProjectService service.
type ProjectServiceClient interface {
	Health(context.Context, *connect.Request[projectpb.HealthRequest]) (*connect.Response[projectpb.HealthResponse], error)
	Platform(context.Context, *connect.Request[projectpb.PlatformRequest]) (*connect.Response[projectpb.PlatformResponse], error)
	ListProjects(context.Context, *connect.Request[projectpb.ListProjectsRequest]) (*connect.Response[projectpb.ListProjectsResponse], error)
	CreateProject(context.Context, *connect.Request[projectpb.CreateProjectRequest]) (*connect.Response[projectpb.CreateProjectResponse], error)
	DeleteProject(context.Context, *connect.Request[projectpb.DeleteProjectRequest]) (*connect.Response[projectpb.DeleteProjectResponse], error)
	IsProjectDeleting(context.Context, *connect.Request[projectpb.IsProjectDeletingRequest]) (*connect.Response[projectpb.IsProjectDeletingResponse], error)
	ProjectExists(context.Context, *connect.Request[projectpb.ProjectExistsRequest]) (*connect.Response[projectpb.ProjectExistsResponse], error)
	GetProjectRepository(context.Context, *connect.Request[projectpb.GetProjectRepositoryRequest]) (*connect.Response[projectpb.GetProjectRepositoryResponse], error)
	UpsertProjectRepository(context.Context, *connect.Request[projectpb.UpsertProjectRepositoryRequest]) (*connect.Response[projectpb.UpsertProjectRepositoryResponse], error)
	CreateProjectDeleteOperation(context.Context, *connect.Request[projectpb.CreateProjectDeleteOperationRequest]) (*connect.Response[projectpb.CreateProjectDeleteOperationResponse], error)
}

// NewProjectServiceClient constructs a client for the dcloud.project.v1.ProjectService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	projectServiceMethods := projectpb.File_project_proto.Services().ByName("ProjectService").Methods()
	return &projectServiceClient{
		health: connect.NewClient[projectpb.HealthRequest, projectpb.HealthResponse](
			httpClient,
			baseURL+ProjectServiceHealthProcedure,
			connect.WithSchema(projectServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
		platform: connect.NewClient[projectpb.PlatformRequest, projectpb.PlatformResponse](
			httpClient,
			baseURL+ProjectServicePlatformProcedure,
			connect.WithSchema(projectServiceMethods.ByName("Platform")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[projectpb.ListProjectsRequest, projectpb.ListProjectsResponse](
			httpClient,
			baseURL+ProjectServiceListProjectsProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		createProject: connect.NewClient[projectpb.CreateProjectRequest, projectpb.CreateProjectResponse](
			httpClient,
			baseURL+ProjectServiceCreateProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("CreateProject")),
			connect.WithClientOptions(opts...),
		),
		deleteProject: connect.NewClient[projectpb.DeleteProjectRequest, projectpb.DeleteProjectResponse](
			httpClient,
			baseURL+ProjectServiceDeleteProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("DeleteProject")),
			connect.WithClientOptions(opts...),
		),
		isProjectDeleting: connect.NewClient[projectpb.IsProjectDeletingRequest, projectpb.IsProjectDeletingResponse](
			httpClient,
			baseURL+ProjectServiceIsProjectDeletingProcedure,
			connect.WithSchema(projectServiceMethods.ByName("IsProjectDeleting")),
			connect.WithClientOptions(opts...),
		),
		projectExists: connect.NewClient[projectpb.ProjectExistsRequest, projectpb.ProjectExistsResponse](
			httpClient,
			baseURL+ProjectServiceProjectExistsProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ProjectExists")),
			connect.WithClientOptions(opts...),
		),
		getProjectRepository: connect.NewClient[projectpb.GetProjectRepositoryRequest, projectpb.GetProjectRepositoryResponse](
			httpClient,
			baseURL+ProjectServiceGetProjectRepositoryProcedure,
			connect.WithSchema(projectServiceMethods.ByName("GetProjectRepository")),
			connect.WithClientOptions(opts...),
		),
		upsertProjectRepository: connect.NewClient[projectpb.UpsertProjectRepositoryRequest, projectpb.UpsertProjectRepositoryResponse](
			httpClient,
			baseURL+ProjectServiceUpsertProjectRepositoryProcedure,
			connect.WithSchema(projectServiceMethods.ByName("UpsertProjectRepository")),
			connect.WithClientOptions(opts...),
		),
		createProjectDeleteOperation: connect.NewClient[projectpb.CreateProjectDeleteOperationRequest, projectpb.CreateProjectDeleteOperationResponse](
			httpClient,
			baseURL+ProjectServiceCreateProjectDeleteOperationProcedure,
			connect.WithSchema(projectServiceMethods.ByName("CreateProjectDeleteOperation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// projectServiceClient implements ProjectServiceClient.
type projectServiceClient struct {
	health                       *connect.Client[projectpb.HealthRequest, projectpb.HealthResponse]
	platform                     *connect.Client[projectpb.PlatformRequest, projectpb.PlatformResponse]
	listProjects                 *connect.Client[projectpb.ListProjectsRequest, projectpb.ListProjectsResponse]
	createProject                *connect.Client[projectpb.CreateProjectRequest, projectpb.CreateProjectResponse]
	deleteProject                *connect.Client[projectpb.DeleteProjectRequest, projectpb.DeleteProjectResponse]
	isProjectDeleting            *connect.Client[projectpb.IsProjectDeletingRequest, projectpb.IsProjectDeletingResponse]
	projectExists                *connect.Client[projectpb.ProjectExistsRequest, projectpb.ProjectExistsResponse]
	getProjectRepository         *connect.Client[projectpb.GetProjectRepositoryRequest, projectpb.GetProjectRepositoryResponse]
	upsertProjectRepository      *connect.Client[projectpb.UpsertProjectRepositoryRequest, projectpb.UpsertProjectRepositoryResponse]
	createProjectDeleteOperation *connect.Client[projectpb.CreateProjectDeleteOperationRequest, projectpb.CreateProjectDeleteOperationResponse]
}

// Health calls dcloud.project.v1.ProjectService.Health.
func (c *projectServiceClient) Health(ctx context.Context, req *connect.Request[projectpb.HealthRequest]) (*connect.Response[projectpb.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// Platform calls dcloud.project.v1.ProjectService.Platform.
func (c *projectServiceClient) Platform(ctx context.Context, req *connect.Request[projectpb.PlatformRequest]) (*connect.Response[projectpb.PlatformResponse], error) {
	return c.platform.CallUnary(ctx, req)
}

// ListProjects calls dcloud.project.v1.ProjectService.ListProjects.
func (c *projectServiceClient) ListProjects(ctx context.Context, req *connect.Request[projectpb.ListProjectsRequest]) (*connect.Response[projectpb.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// CreateProject calls dcloud.project.v1.ProjectService.CreateProject.
func (c *projectServiceClient) CreateProject(ctx context.Context, req *connect.Request[projectpb.CreateProjectRequest]) (*connect.Response[projectpb.CreateProjectResponse], error) {
	return c.createProject.CallUnary(ctx, req)
}

// DeleteProject calls dcloud.project.v1.ProjectService.DeleteProject.
func (c *projectServiceClient) DeleteProject(ctx context.Context, req *connect.Request[projectpb.DeleteProjectRequest]) (*connect.Response[projectpb.DeleteProjectResponse], error) {
	return c.deleteProject.CallUnary(ctx, req)
}

// IsProjectDeleting calls dcloud.project.v1.ProjectService.IsProjectDeleting.
func (c *projectServiceClient) IsProjectDeleting(ctx context.Context, req *connect.Request[projectpb.IsProjectDeletingRequest]) (*connect.Response[projectpb.IsProjectDeletingResponse], error) {
	return c.isProjectDeleting.CallUnary(ctx, req)
}

// ProjectExists calls dcloud.project.v1.ProjectService.ProjectExists.
func (c *projectServiceClient) ProjectExists(ctx context.Context, req *connect.Request[projectpb.ProjectExistsRequest]) (*connect.Response[projectpb.ProjectExistsResponse], error) {
	return c.projectExists.CallUnary(ctx, req)
}

// GetProjectRepository calls dcloud.project.v1.ProjectService.GetProjectRepository.
func (c *projectServiceClient) GetProjectRepository(ctx context.Context, req *connect.Request[projectpb.GetProjectRepositoryRequest]) (*connect.Response[projectpb.GetProjectRepositoryResponse], error) {
	return c.getProjectRepository.CallUnary(ctx, req)
}

// UpsertProjectRepository calls dcloud.project.v1.ProjectService.UpsertProjectRepository.
func (c *projectServiceClient) UpsertProjectRepository(ctx context.Context, req *connect.Request[projectpb.UpsertProjectRepositoryRequest]) (*connect.Response[projectpb.UpsertProjectRepositoryResponse], error) {
	return c.upsertProjectRepository.CallUnary(ctx, req)
}

// CreateProjectDeleteOperation calls dcloud.project.v1.ProjectService.CreateProjectDeleteOperation.
func (c *projectServiceClient) CreateProjectDeleteOperation(ctx context.Context, req *connect.Request[projectpb.CreateProjectDeleteOperationRequest]) (*connect.Response[projectpb.CreateProjectDeleteOperationResponse], error) {
	return c.createProjectDeleteOperation.CallUnary(ctx, req)
}

// ProjectServiceHandler is an implementation of the dcloud.project.v1.ProjectService service.
type ProjectServiceHandler interface {
	Health(context.Context, *connect.Request[projectpb.HealthRequest]) (*connect.Response[projectpb.HealthResponse], error)
	Platform(context.Context, *connect.Request[projectpb.PlatformRequest]) (*connect.Response[projectpb.PlatformResponse], error)
	ListProjects(context.Context, *connect.Request[projectpb.ListProjectsRequest]) (*connect.Response[projectpb.ListProjectsResponse], error)
	CreateProject(context.Context, *connect.Request[projectpb.CreateProjectRequest]) (*connect.Response[projectpb.CreateProjectResponse], error)
	DeleteProject(context.Context, *connect.Request[projectpb.DeleteProjectRequest]) (*connect.Response[projectpb.DeleteProjectResponse], error)
	IsProjectDeleting(context.Context, *connect.Request[projectpb.IsProjectDeletingRequest]) (*connect.Response[projectpb.IsProjectDeletingResponse], error)
	ProjectExists(context.Context, *connect.Request[projectpb.ProjectExistsRequest]) (*connect.Response[projectpb.ProjectExistsResponse], error)
	GetProjectRepository(context.Context, *connect.Request[projectpb.GetProjectRepositoryRequest]) (*connect.Response[projectpb.GetProjectRepositoryResponse], error)
	UpsertProjectRepository(context.Context, *connect.Request[projectpb.UpsertProjectRepositoryRequest]) (*connect.Response[projectpb.UpsertProjectRepositoryResponse], error)
	CreateProjectDeleteOperation(context.Context, *connect.Request[projectpb.CreateProjectDeleteOperationRequest]) (*connect.Response[projectpb.CreateProjectDeleteOperationResponse], error)
}

// NewProjectServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProjectServiceHandler(svc ProjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	projectServiceMethods := projectpb.File_project_proto.Services().ByName("ProjectService").Methods()
	projectServiceHealthHandler := connect.NewUnaryHandler(
		ProjectServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(projectServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	projectServicePlatformHandler := connect.NewUnaryHandler(
		ProjectServicePlatformProcedure,
		svc.Platform,
		connect.WithSchema(projectServiceMethods.ByName("Platform")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceListProjectsHandler := connect.NewUnaryHandler(
		ProjectServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(projectServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceCreateProjectHandler := connect.NewUnaryHandler(
		ProjectServiceCreateProjectProcedure,
		svc.CreateProject,
		connect.WithSchema(projectServiceMethods.ByName("CreateProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceDeleteProjectHandler := connect.NewUnaryHandler(
		ProjectServiceDeleteProjectProcedure,
		svc.DeleteProject,
		connect.WithSchema(projectServiceMethods.ByName("DeleteProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceIsProjectDeletingHandler := connect.NewUnaryHandler(
		ProjectServiceIsProjectDeletingProcedure,
		svc.IsProjectDeleting,
		connect.WithSchema(projectServiceMethods.ByName("IsProjectDeleting")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceProjectExistsHandler := connect.NewUnaryHandler(
		ProjectServiceProjectExistsProcedure,
		svc.ProjectExists,
		connect.WithSchema(projectServiceMethods.ByName("ProjectExists")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceGetProjectRepositoryHandler := connect.NewUnaryHandler(
		ProjectServiceGetProjectRepositoryProcedure,
		svc.GetProjectRepository,
		connect.WithSchema(projectServiceMethods.ByName("GetProjectRepository")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceUpsertProjectRepositoryHandler := connect.NewUnaryHandler(
		ProjectServiceUpsertProjectRepositoryProcedure,
		svc.UpsertProjectRepository,
		connect.WithSchema(projectServiceMethods.ByName("UpsertProjectRepository")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceCreateProjectDeleteOperationHandler := connect.NewUnaryHandler(
		ProjectServiceCreateProjectDeleteOperationProcedure,
		svc.CreateProjectDeleteOperation,
		connect.WithSchema(projectServiceMethods.ByName("CreateProjectDeleteOperation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dcloud.project.v1.ProjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProjectServiceHealthProcedure:
			projectServiceHealthHandler.ServeHTTP(w, r)
		case ProjectServicePlatformProcedure:
			projectServicePlatformHandler.ServeHTTP(w, r)
		case ProjectServiceListProjectsProcedure:
			projectServiceListProjectsHandler.ServeHTTP(w, r)
		case ProjectServiceCreateProjectProcedure:
			projectServiceCreateProjectHandler.ServeHTTP(w, r)
		case ProjectServiceDeleteProjectProcedure:
			projectServiceDeleteProjectHandler.ServeHTTP(w, r)
		case ProjectServiceIsProjectDeletingProcedure:
			projectServiceIsProjectDeletingHandler.ServeHTTP(w, r)
		case ProjectServiceProjectExistsProcedure:
			projectServiceProjectExistsHandler.ServeHTTP(w, r)
		case ProjectServiceGetProjectRepositoryProcedure:
			projectServiceGetProjectRepositoryHandler.ServeHTTP(w, r)
		case ProjectServiceUpsertProjectRepositoryProcedure:
			projectServiceUpsertProjectRepositoryHandler.ServeHTTP(w, r)
		case ProjectServiceCreateProjectDeleteOperationProcedure:
			projectServiceCreateProjectDeleteOperationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectServiceHandler struct{}

func (UnimplementedProjectServiceHandler) Health(context.Context, *connect.Request[projectpb.HealthRequest]) (*connect.Response[projectpb.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.project.v1.ProjectService.Health is not implemented"))
}

func (UnimplementedProjectServiceHandler) Platform(context.Context, *connect.Request[projectpb.PlatformRequest]) (*connect.Response[projectpb.PlatformResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.project.v1.ProjectService.Platform is not implemented"))
}

func (UnimplementedProjectServiceHandler) ListProjects(context.Context, *connect.Request[projectpb.ListProjectsRequest]) (*connect.Response[projectpb.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.project.v1.ProjectService.ListProjects is not implemented"))
}

func (UnimplementedProjectServiceHandler) CreateProject(context.Context, *connect.Request[projectpb.CreateProjectRequest]) (*connect.Response[projectpb.CreateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.project.v1.ProjectService.CreateProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) DeleteProject(context.Context, *connect.Request[projectpb.DeleteProjectRequest]) (*connect.Response[projectpb.DeleteProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.project.v1.ProjectService.DeleteProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) IsProjectDeleting(context.Context, *connect.Request[projectpb.IsProjectDeletingRequest]) (*connect.Response[projectpb.IsProjectDeletingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.project.v1.ProjectService.IsProjectDeleting is not implemented"))
}

func (UnimplementedProjectServiceHandler) ProjectExists(context.Context, *connect.Request[projectpb.ProjectExistsRequest]) (*connect.Response[projectpb.ProjectExistsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.project.v1.ProjectService.ProjectExists is not implemented"))
}

func (UnimplementedProjectServiceHandler) GetProjectRepository(context.Context, *connect.Request[projectpb.GetProjectRepositoryRequest]) (*connect.Response[projectpb.GetProjectRepositoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.project.v1.ProjectService.GetProjectRepository is not implemented"))
}

func (UnimplementedProjectServiceHandler) UpsertProjectRepository(context.Context, *connect.Request[projectpb.UpsertProjectRepositoryRequest]) (*connect.Response[projectpb.UpsertProjectRepositoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.project.v1.ProjectService.UpsertProjectRepository is not implemented"))
}

func (UnimplementedProjectServiceHandler) CreateProjectDeleteOperation(context.Context, *connect.Request[projectpb.CreateProjectDeleteOperationRequest]) (*connect.Response[projectpb.CreateProjectDeleteOperationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.project.v1.ProjectService.CreateProjectDeleteOperation is not implemented"))
}
