// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: storage.proto

package storagepbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	storagepb "github.com/daigo-suhara/dcloud/internal/pb/storagepb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ObjectStorageServiceName is the fully-qualified name of the ObjectStorageService service.
	ObjectStorageServiceName = "dcloud.storage.v1.ObjectStorageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ObjectStorageServiceHealthProcedure is the fully-qualified name of the ObjectStorageService's
	// Health RPC.
	ObjectStorageServiceHealthProcedure = "/dcloud.storage.v1.ObjectStorageService/Health"
	// ObjectStorageServiceListBucketsProcedure is the fully-qualified name of the
	// ObjectStorageService's ListBuckets RPC.
	ObjectStorageServiceListBucketsProcedure = "/dcloud.storage.v1.ObjectStorageService/ListBuckets"
	// ObjectStorageServiceCreateBucketProcedure is the fully-qualified name of the
	// ObjectStorageService's CreateBucket RPC.
	ObjectStorageServiceCreateBucketProcedure = "/dcloud.storage.v1.ObjectStorageService/CreateBucket"
	// ObjectStorageServiceDeleteBucketProcedure is the fully-qualified name of the
	// ObjectStorageService's DeleteBucket RPC.
	ObjectStorageServiceDeleteBucketProcedure = "/dcloud.storage.v1.ObjectStorageService/DeleteBucket"
	// ObjectStorageServiceGetBucketCredentialsProcedure is the fully-qualified name of the
	// ObjectStorageService's GetBucketCredentials RPC.
	ObjectStorageServiceGetBucketCredentialsProcedure = "/dcloud.storage.v1.ObjectStorageService/GetBucketCredentials"
	// ObjectStorageServiceGetOperationProcedure is the fully-qualified name of the
	// ObjectStorageService's GetOperation RPC.
	ObjectStorageServiceGetOperationProcedure = "/dcloud.storage.v1.ObjectStorageService/GetOperation"
)

// ObjectStorageServiceClient is a client for the dcloud.storage.v1.ObjectStorageService service.
type ObjectStorageServiceClient interface {
	Health(context.Context, *connect.Request[storagepb.HealthRequest]) (*connect.Response[storagepb.HealthResponse], error)
	ListBuckets(context.Context, *connect.Request[storagepb.ListBucketsRequest]) (*connect.Response[storagepb.ListBucketsResponse], error)
	CreateBucket(context.Context, *connect.Request[storagepb.CreateBucketRequest]) (*connect.Response[storagepb.CreateBucketResponse], error)
	DeleteBucket(context.Context, *connect.Request[storagepb.DeleteBucketRequest]) (*connect.Response[storagepb.DeleteBucketResponse], error)
	GetBucketCredentials(context.Context, *connect.Request[storagepb.GetBucketCredentialsRequest]) (*connect.Response[storagepb.GetBucketCredentialsResponse], error)
	GetOperation(context.Context, *connect.Request[storagepb.GetOperationRequest]) (*connect.Response[storagepb.GetOperationResponse], error)
}

// NewObjectStorageServiceClient constructs a client for the dcloud.storage.v1.ObjectStorageService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewObjectStorageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ObjectStorageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	objectStorageServiceMethods := storagepb.File_storage_proto.Services().ByName("ObjectStorageService").Methods()
	return &objectStorageServiceClient{
		health: connect.NewClient[storagepb.HealthRequest, storagepb.HealthResponse](
			httpClient,
			baseURL+ObjectStorageServiceHealthProcedure,
			connect.WithSchema(objectStorageServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
		listBuckets: connect.NewClient[storagepb.ListBucketsRequest, storagepb.ListBucketsResponse](
			httpClient,
			baseURL+ObjectStorageServiceListBucketsProcedure,
			connect.WithSchema(objectStorageServiceMethods.ByName("ListBuckets")),
			connect.WithClientOptions(opts...),
		),
		createBucket: connect.NewClient[storagepb.CreateBucketRequest, storagepb.CreateBucketResponse](
			httpClient,
			baseURL+ObjectStorageServiceCreateBucketProcedure,
			connect.WithSchema(objectStorageServiceMethods.ByName("CreateBucket")),
			connect.WithClientOptions(opts...),
		),
		deleteBucket: connect.NewClient[storagepb.DeleteBucketRequest, storagepb.DeleteBucketResponse](
			httpClient,
			baseURL+ObjectStorageServiceDeleteBucketProcedure,
			connect.WithSchema(objectStorageServiceMethods.ByName("DeleteBucket")),
			connect.WithClientOptions(opts...),
		),
		getBucketCredentials: connect.NewClient[storagepb.GetBucketCredentialsRequest, storagepb.GetBucketCredentialsResponse](
			httpClient,
			baseURL+ObjectStorageServiceGetBucketCredentialsProcedure,
			connect.WithSchema(objectStorageServiceMethods.ByName("GetBucketCredentials")),
			connect.WithClientOptions(opts...),
		),
		getOperation: connect.NewClient[storagepb.GetOperationRequest, storagepb.GetOperationResponse](
			httpClient,
			baseURL+ObjectStorageServiceGetOperationProcedure,
			connect.WithSchema(objectStorageServiceMethods.ByName("GetOperation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// objectStorageServiceClient implements ObjectStorageServiceClient.
type objectStorageServiceClient struct {
	health               *connect.Client[storagepb.HealthRequest, storagepb.HealthResponse]
	listBuckets          *connect.Client[storagepb.ListBucketsRequest, storagepb.ListBucketsResponse]
	createBucket         *connect.Client[storagepb.CreateBucketRequest, storagepb.CreateBucketResponse]
	deleteBucket         *connect.Client[storagepb.DeleteBucketRequest, storagepb.DeleteBucketResponse]
	getBucketCredentials *connect.Client[storagepb.GetBucketCredentialsRequest, storagepb.GetBucketCredentialsResponse]
	getOperation         *connect.Client[storagepb.GetOperationRequest, storagepb.GetOperationResponse]
}

// Health calls dcloud.storage.v1.ObjectStorageService.Health.
func (c *objectStorageServiceClient) Health(ctx context.Context, req *connect.Request[storagepb.HealthRequest]) (*connect.Response[storagepb.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// ListBuckets calls dcloud.storage.v1.ObjectStorageService.ListBuckets.
func (c *objectStorageServiceClient) ListBuckets(ctx context.Context, req *connect.Request[storagepb.ListBucketsRequest]) (*connect.Response[storagepb.ListBucketsResponse], error) {
	return c.listBuckets.CallUnary(ctx, req)
}

// CreateBucket calls dcloud.storage.v1.ObjectStorageService.CreateBucket.
func (c *objectStorageServiceClient) CreateBucket(ctx context.Context, req *connect.Request[storagepb.CreateBucketRequest]) (*connect.Response[storagepb.CreateBucketResponse], error) {
	return c.createBucket.CallUnary(ctx, req)
}

// DeleteBucket calls dcloud.storage.v1.ObjectStorageService.DeleteBucket.
func (c *objectStorageServiceClient) DeleteBucket(ctx context.Context, req *connect.Request[storagepb.DeleteBucketRequest]) (*connect.Response[storagepb.DeleteBucketResponse], error) {
	return c.deleteBucket.CallUnary(ctx, req)
}

// GetBucketCredentials calls dcloud.storage.v1.ObjectStorageService.GetBucketCredentials.
func (c *objectStorageServiceClient) GetBucketCredentials(ctx context.Context, req *connect.Request[storagepb.GetBucketCredentialsRequest]) (*connect.Response[storagepb.GetBucketCredentialsResponse], error) {
	return c.getBucketCredentials.CallUnary(ctx, req)
}

// GetOperation calls dcloud.storage.v1.ObjectStorageService.GetOperation.
func (c *objectStorageServiceClient) GetOperation(ctx context.Context, req *connect.Request[storagepb.GetOperationRequest]) (*connect.Response[storagepb.GetOperationResponse], error) {
	return c.getOperation.CallUnary(ctx, req)
}

// ObjectStorageServiceHandler is an implementation of the dcloud.storage.v1.ObjectStorageService
// service.
type ObjectStorageServiceHandler interface {
	Health(context.Context, *connect.Request[storagepb.HealthRequest]) (*connect.Response[storagepb.HealthResponse], error)
	ListBuckets(context.Context, *connect.Request[storagepb.ListBucketsRequest]) (*connect.Response[storagepb.ListBucketsResponse], error)
	CreateBucket(context.Context, *connect.Request[storagepb.CreateBucketRequest]) (*connect.Response[storagepb.CreateBucketResponse], error)
	DeleteBucket(context.Context, *connect.Request[storagepb.DeleteBucketRequest]) (*connect.Response[storagepb.DeleteBucketResponse], error)
	GetBucketCredentials(context.Context, *connect.Request[storagepb.GetBucketCredentialsRequest]) (*connect.Response[storagepb.GetBucketCredentialsResponse], error)
	GetOperation(context.Context, *connect.Request[storagepb.GetOperationRequest]) (*connect.Response[storagepb.GetOperationResponse], error)
}

// NewObjectStorageServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewObjectStorageServiceHandler(svc ObjectStorageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	objectStorageServiceMethods := storagepb.File_storage_proto.Services().ByName("ObjectStorageService").Methods()
	objectStorageServiceHealthHandler := connect.NewUnaryHandler(
		ObjectStorageServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(objectStorageServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	objectStorageServiceListBucketsHandler := connect.NewUnaryHandler(
		ObjectStorageServiceListBucketsProcedure,
		svc.ListBuckets,
		connect.WithSchema(objectStorageServiceMethods.ByName("ListBuckets")),
		connect.WithHandlerOptions(opts...),
	)
	objectStorageServiceCreateBucketHandler := connect.NewUnaryHandler(
		ObjectStorageServiceCreateBucketProcedure,
		svc.CreateBucket,
		connect.WithSchema(objectStorageServiceMethods.ByName("CreateBucket")),
		connect.WithHandlerOptions(opts...),
	)
	objectStorageServiceDeleteBucketHandler := connect.NewUnaryHandler(
		ObjectStorageServiceDeleteBucketProcedure,
		svc.DeleteBucket,
		connect.WithSchema(objectStorageServiceMethods.ByName("DeleteBucket")),
		connect.WithHandlerOptions(opts...),
	)
	objectStorageServiceGetBucketCredentialsHandler := connect.NewUnaryHandler(
		ObjectStorageServiceGetBucketCredentialsProcedure,
		svc.GetBucketCredentials,
		connect.WithSchema(objectStorageServiceMethods.ByName("GetBucketCredentials")),
		connect.WithHandlerOptions(opts...),
	)
	objectStorageServiceGetOperationHandler := connect.NewUnaryHandler(
		ObjectStorageServiceGetOperationProcedure,
		svc.GetOperation,
		connect.WithSchema(objectStorageServiceMethods.ByName("GetOperation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dcloud.storage.v1.ObjectStorageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ObjectStorageServiceHealthProcedure:
			objectStorageServiceHealthHandler.ServeHTTP(w, r)
		case ObjectStorageServiceListBucketsProcedure:
			objectStorageServiceListBucketsHandler.ServeHTTP(w, r)
		case ObjectStorageServiceCreateBucketProcedure:
			objectStorageServiceCreateBucketHandler.ServeHTTP(w, r)
		case ObjectStorageServiceDeleteBucketProcedure:
			objectStorageServiceDeleteBucketHandler.ServeHTTP(w, r)
		case ObjectStorageServiceGetBucketCredentialsProcedure:
			objectStorageServiceGetBucketCredentialsHandler.ServeHTTP(w, r)
		case ObjectStorageServiceGetOperationProcedure:
			objectStorageServiceGetOperationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedObjectStorageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedObjectStorageServiceHandler struct{}

func (UnimplementedObjectStorageServiceHandler) Health(context.Context, *connect.Request[storagepb.HealthRequest]) (*connect.Response[storagepb.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.storage.v1.ObjectStorageService.Health is not implemented"))
}

func (UnimplementedObjectStorageServiceHandler) ListBuckets(context.Context, *connect.Request[storagepb.ListBucketsRequest]) (*connect.Response[storagepb.ListBucketsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.storage.v1.ObjectStorageService.ListBuckets is not implemented"))
}

func (UnimplementedObjectStorageServiceHandler) CreateBucket(context.Context, *connect.Request[storagepb.CreateBucketRequest]) (*connect.Response[storagepb.CreateBucketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.storage.v1.ObjectStorageService.CreateBucket is not implemented"))
}

func (UnimplementedObjectStorageServiceHandler) DeleteBucket(context.Context, *connect.Request[storagepb.DeleteBucketRequest]) (*connect.Response[storagepb.DeleteBucketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.storage.v1.ObjectStorageService.DeleteBucket is not implemented"))
}

func (UnimplementedObjectStorageServiceHandler) GetBucketCredentials(context.Context, *connect.Request[storagepb.GetBucketCredentialsRequest]) (*connect.Response[storagepb.GetBucketCredentialsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.storage.v1.ObjectStorageService.GetBucketCredentials is not implemented"))
}

func (UnimplementedObjectStorageServiceHandler) GetOperation(context.Context, *connect.Request[storagepb.GetOperationRequest]) (*connect.Response[storagepb.GetOperationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dcloud.storage.v1.ObjectStorageService.GetOperation is not implemented"))
}
